### PR TITLE
Remove 'ecma_assert_object_type_is_valid' from release

### PR DESCRIPTION
**Pull request by LaszloLango**
JerryScript-DCO-1.0-Signed-off-by: László Langó llango.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by zherczeg** [comment]
Currently it is not possible to create an object with invalid type

**Comment by LaszloLango** [comment]
@zherczeg, I was also thinking about removing this function completely if that is you tried to say :)

**Comment by zherczeg** [comment]
LGTM

**Comment by akiss77** [comment]
LGTM

**Pull request merged**
