### PR TITLE
Add some asserts to check heap structure consistency

### PR DESCRIPTION
**Pull request by dbatyai**
JerryScript-DCO-1.0-Signed-off-by: Dániel Bátyai dbatyai@inf.u-szeged.hu

### CODE REVIEW

**Comment by dbatyai** [comment]
Currently if the structure gets corrupted for some reason, it can produce strange errors in different places, which can be hard to debug. These asserts should help with this.

**Comment by kkristof** [comment]
Looks good to me

**Comment by akiss77** [comment]
LGTM FWIW

**Comment by LaszloLango** [comment]
LGTM

**Comment by zherczeg** [comment]
LGTM

**Pull request merged**
