### PR TITLE
Factor out common error dispatch call functionality into helper

### PR DESCRIPTION
**Pull request by akiss77**
JerryScript-DCO-1.0-Signed-off-by: Akos Kiss akiss@inf.u-szeged.hu

### CODE REVIEW

**Comment by zherczeg** [comment]
Nice catch. How much does it affect binary size?

**Comment by akiss77** [comment]
@zherczeg In release LTO, cca. 500 bytes of text gained on arm-linux and 300-500 bytes on arm-mcu. 2K+ in debug.

**Comment by LaszloLango** [comment]
LGTM

**Comment by zherczeg** [comment]
LGTM

**Pull request merged**
