### PR TITLE
Remove the unused LIT_STRING_HASH_LAST_BYTES_COUNT define macro

### PR DESCRIPTION
**Pull request by robertsipka**
JerryScript-DCO-1.0-Signed-off-by: Robert Sipka rsipka.uszeged@partner.samsung.com

### CODE REVIEW

**Comment by zherczeg** [comment]
LGTM

**Comment by akiss77** [comment]
LGTM (FWIW)
Except that it's a macro, not a variable. Please, change the commit title.

**Comment by robertsipka** [comment]
thanks, I've updated the commit title.

**Comment by LaszloLango** [comment]
LGTM

**Pull request merged**
