### PR TITLE
Fixes for URI decoding.

### PR DESCRIPTION
**Pull request by zherczeg**
JerryScript-DCO-1.0-Signed-off-by: Zoltan Herczeg zherczeg@inf.u-szeged.hu

### CODE REVIEW

**Comment by zherczeg** [comment]
Fixes four ecma262 tests.

**Comment by egavrin** [comment]
Good to me

**Comment by galpeter** [comment]
looks good to me

**Comment by zherczeg** [comment]
Thank you. Shall I push it?

**Comment by zherczeg** [comment]
Landed in 2630048eccab104d00146c7aabdfea985663da82

**Pull request closed without merging**
