### PR TITLE
Fix 'control reaches end of non-void function' compile error for 'noreturn'

### PR DESCRIPTION
**Pull request by seanshpark**
JerryScript-DCO-1.0-Signed-off-by: SaeHie Park saehie.park@samsung.com

### CODE REVIEW

**Comment by egavrin** [comment]
`__builtin_unreachable();` didn't work?

**Comment by seanshpark** [comment]
sorry but cannot find `__builtin_unreachable()`. 
you mean to add `__builtin_unreachable` function with `while(true) {}` ?

**Comment by zherczeg** [comment]
What I don't understand is: this function has actually returns with void

**Comment by seanshpark** [comment]
@zherczeg , can you describe more about `this function` ?

**Comment by zherczeg** [comment]
It is called when there is a fatal error, and the engine should stop. The function is void.
Why the compiler says it is a non-void function???

**Comment by seanshpark** [comment]
I think not the compiler(mips-sde-elf-gcc), but the function `abort()` or `exit()` in the RTOS I'm working on may return. I do not have the source code thus cannot confirm, and cause of same reason, cannot fix that platform.
I don't like this approach, fixing JerryScript, but for now I can't think of better one.

**Comment by seanshpark** [comment]
Accept or Reject?

**Comment by ruben-ayrapetyan** [comment]
Looks good to me

**Comment by zherczeg** [comment]
lgtm

**Comment by seanshpark** [comment]
Thank you :)

**Pull request merged**
