### PR TITLE
Fix assertion 'ret_value == ecma_make_empty_completion_value ()' fail in JSON

### PR DESCRIPTION
**Pull request by rtakacs**
Added missing ecma_is_completion_value_empty checks.

### CODE REVIEW

**Comment by zherczeg** [comment]
I don't like that space type is ecma_value_t first and int32_t later. I would rename one of them to something else. Otherwise LGTM.

**Comment by ruben-ayrapetyan** [comment]
Looks good to me

**Comment by egavrin** [comment]
`make push`

**Comment by dbatyai** [comment]
Landed: c4b1f02947aee10f8ca20ea17da340f8c5fe5a3a

**Pull request closed without merging**
