### PR TITLE
Fix ecma_op_array_object_define_own_property

### PR DESCRIPTION
**Pull request by kkristof**
JerryScript-DCO-1.0-Signed-off-by: Kristof Kosztyo kkosztyo.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by kkristof** [comment]
Check the ecma standard here: http://ecma-international.org/ecma-262/5.1/#sec-15.4.5.1
It also fixes the following test262 tests:
ch15/15.2/15.2.3/15.2.3.6/15.2.3.6-4-339-3
ch15/15.2/15.2.3/15.2.3.6/15.2.3.6-4-34
ch15/15.2/15.2.3/15.2.3.6/15.2.3.6-4-547-3

**Comment by ruben-ayrapetyan** [comment]
Looks good to me.

**Comment by egavrin** [comment]
Great. `make push`

**Comment by dbatyai** [comment]
lgtm

**Pull request merged**
