### PR TITLE
Fix dump of arguments / eval usage hint in preparse_scope

### PR DESCRIPTION
**Pull request by ruben-ayrapetyan**

### CODE REVIEW

**Comment by egavrin** [comment]
Fix unittest for parser and Ok for me

**Comment by egavrin** [comment]
Good to me

**Comment by zherczeg** [comment]
LGTM

**Comment by ruben-ayrapetyan** [comment]
// During last rebase I've incorrectly updated the changes so that patch #369 was reverted.

**Comment by ruben-ayrapetyan** [comment]
> // During last rebase I've incorrectly updated the changes so that patch #369 was reverted.

The patch was restored with #409 (4fdb5249b99122a074f5b6adb13fcfdccf722ad6).

**Pull request merged**
