### PR TITLE
Remove intrinsics (native_call opcode)

### PR DESCRIPTION
**Pull request by ruben-ayrapetyan**

### CODE REVIEW

**Comment by egavrin** [comment]
Nearly perfect patch! Good to me.

PS should be merged after #499

**Comment by galpeter** [comment]
If I only take into account the intrinsic removal on this branch then it's ok. But before this we need make the `print` function.

**Comment by egavrin** [comment]
`make push`

**Comment by ruben-ayrapetyan** [comment]
Merged (f7781bb7bcfeee5913cf772d3b577e9798040b7f).

**Pull request closed without merging**
