### PR TITLE
Fix pass of USE_COMPILER_DEFAULT_LIBC from `make` (Makefile) to `cmake` (CMakeLists.txt)

### PR DESCRIPTION
**Pull request by ruben-ayrapetyan**

### CODE REVIEW

**Comment by egavrin** [comment]
Good to me.

PS How did this work for IoTjs?

**Comment by ruben-ayrapetyan** [comment]
@egavrin, IoTjs calls `cmake` directly, without `make`.

**Comment by galpeter** [comment]
lgtm

**Comment by egavrin** [comment]
`make push`

**Pull request merged**
