### PR TITLE
Remove allocator functions which stores size.

### PR DESCRIPTION
**Pull request by zherczeg**

### CODE REVIEW

**Comment by LaszloLango** [comment]
I thought those function are faster, than those which doesn't store size. Could you share the measurement results? What are the goal of this PR? Code cleaning?

**Comment by zherczeg** [comment]
No. They are slower.  Jerry allocator does not store size by default, and storing the size requires a helper, which allocates an extra 4 byte block to store the size (extra overhead, extra memory, and returns with 4 byte aligned block). There were some cases which used this utility but they were removed, since this is inefficient. Now I removed the last use case,. and the allocator helpers with it.

**Comment by LaszloLango** [comment]
FYI: RPi2 results:

Benchmark | RSS (bytes) | Perf (sec) |
----: | ----: | ----: | 
3d-cube.js | 57344 -> 57344 : 0.000% | 0.945 -> 0.943 : +0.154% | 
3d-raytrace.js | 217088 -> 217088 : 0.000% | 1.125 -> 1.123 : +0.108% | 
access-binary-trees.js | 53248 -> 53248 : 0.000% | 0.600 -> 0.591 : +1.338% | 
access-fannkuch.js | 24576 -> 24576 : 0.000% | 2.423 -> 2.363 : +2.494% | 
access-nbody.js | 28672 -> 28672 : 0.000% | 1.080 -> 1.077 : +0.230% | 
bitops-3bit-bits-in-byte.js | 16384 -> 16384 : 0.000% | 0.581 -> 0.591 : -1.715% | 
bitops-bits-in-byte.js | 16384 -> 16384 : 0.000% | 0.861 -> 0.859 : +0.217% | 
bitops-bitwise-and.js | 16384 -> 16384 : 0.000% | 0.975 -> 0.934 : +4.247% | 
bitops-nsieve-bits.js | 155648 -> 155648 : 0.000% | 1.891 -> 1.787 : +5.477% | 
controlflow-recursive.js | 98304 -> 94208 : +4.167% | 0.382 -> 0.399 : -4.630% | 
crypto-aes.js | 94208 -> 94208 : 0.000% | 1.134 -> 1.114 : +1.753% | 
crypto-md5.js | 167936 -> 163840 : +2.439% | 0.759 -> 0.738 : +2.742% | 
crypto-sha1.js | 110592 -> 110592 : 0.000% | 0.727 -> 0.705 : +2.975% | 
date-format-tofte.js | 40960 -> 40960 : 0.000% | 0.871 -> 0.865 : +0.717% | 
date-format-xparb.js | 49152 -> 49152 : 0.000% | 0.468 -> 0.470 : -0.379% | 
math-cordic.js | 20480 -> 20480 : 0.000% | 1.388 -> 1.345 : +3.095% | 
math-partial-sums.js | 20480 -> 16384 : +20.000% | 0.738 -> 0.708 : +4.051% | 
math-spectral-norm.js | 24576 -> 24576 : 0.000% | 0.583 -> 0.600 : -2.783% | 
string-base64.js | 147456 -> 143360 : +2.778% | 2.071 -> 2.054 : +0.778% | 
string-fasta.js | 32768 -> 32768 : 0.000% | 1.397 -> 1.403 : -0.399% | 
Geometric mean: | +1.580% | +1.052% | 

Binary sizes (bytes)
823e4d030c:157512
6d571826c0:156952

**Comment by LaszloLango** [comment]
LGTM

**Comment by zherczeg** [comment]
I do think this is just noise.

**Comment by akosthekiss** [comment]
LGTM

**Pull request merged**
