### PR TITLE
Fix Array.prototype.toLocaleString() when toLocaleString returns non-string.

### PR DESCRIPTION
**Pull request by dbatyai**
JerryScript-DCO-1.0-Signed-off-by: Dániel Bátyai dbatyai.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by galpeter** [comment]
looks good to me

**Comment by zherczeg** [comment]
LGTM

**Comment by egavrin** [comment]
Looks good

**Comment by galpeter** [comment]
Landed: https://github.com/Samsung/jerryscript/commit/fc45b805794b335210a989a0a1d6d63598b84f91

**Pull request closed without merging**
