### PR TITLE
Use rcs_record_iterator_t::skip(size_t) instead of its template version.

### PR DESCRIPTION
**Pull request by rtakacs**
JerryScript-DCO-1.0-Signed-off-by: Roland Takacs rtakacs.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by egavrin** [comment]
@rtakacs please share performance measurements and changes in binary size.

**Comment by rtakacs** [comment]
Measurement results:
<pre>
testing board:  rpi2
master revision: 140982e
</pre>

Section | Size
--------- | --------- |
.text | 190732 -> 191092 (-0,188)
.rodata | 8168 -> 8176 (-0,098)

**Note**: the other sections are not modified.

Benchmark | RSS<br>(+ is better) | Perf<br>(+ is better) |
--------- | --- | ---- |
3d-cube.js | 132-> 132 (0.000) | 3.746-> 3.67 (2.029) | 
access-binary-trees.js | 88-> 88 (0.000) | 1.908-> 1.883 (1.310) | 
access-fannkuch.js | 48-> 48 (0.000) | 9.8-> 9.607 (1.969) | 
access-nbody.js | 64-> 64 (0.000) | 4.541-> 4.414 (2.797) | 
bitops-3bit-bits-in-byte.js | 40-> 40 (0.000) | 2.664-> 2.661 (0.113) |
bitops-bits-in-byte.js | 40-> 40 (0.000) | 3.733-> 3.712 (0.563) | 
bitops-bitwise-and.js | 36-> 36 (0.000) | 4.287-> 4.229 (1.353) | 
controlflow-recursive.js | 220-> 220 (0.000) | 1.719-> 1.726 (-0.407) | 
crypto-aes.js | 160-> 160 (0.000) | 6.105-> 6.002 (1.687) | 
crypto-md5.js | 208-> 208 (0.000) | 35.731-> 35.51 (0.619) | 
crypto-sha1.js | 144-> 144 (0.000) | 15.509->15.268 (1.554) | 
date-format-tofte.js | 112-> 112 (0.000) | 4.009-> 4.003 (0.150) | 
date-format-xparb.js | 96-> 96 (0.000) | 2.109-> 2.094 (0.711) | 
math-cordic.js | 48-> 48 (0.000) | 4.006-> 3.985 (0.524) | 
math-partial-sums.js | 44-> 44 (0.000) | 2.332-> 2.304 (1.201) | 
math-spectral-norm.js | 48-> 48 (0.000) | 2.254-> 2.242 (0.532) | 
string-base64.js | 204-> 204 (0.000) | ---
string-fasta.js | 56-> 56 (0.000) | 5.864-> 5.778 (1.467) | 
Geometric mean: | RSS reduction: 0% | Speed up: 1.0721% |

**Note**: all tests ran 10 times. Tests that failed are not shown in the table.

**Comment by tilmannOSG** [comment]
The results look good. Can we get this merged?

**Comment by ruben-ayrapetyan** [comment]
@rtakacs, @tilmannOSG, binary size increases `190732 -> 191092` with the change. Are causes of the increase clear? Could you, please, describe them briefly?

**Comment by tilmannOSG** [comment]
@rtakacs Can you please have a closer look?

**Comment by rtakacs** [comment]
We can close this PR since #791 does this modification.

**Pull request closed without merging**
