### PR TITLE
Avoid `(void) ` and use `JERRY_UNUSED`

### PR DESCRIPTION
**Pull request by akosthekiss**
JerryScript-DCO-1.0-Signed-off-by: Akos Kiss akiss@inf.u-szeged.hu

### CODE REVIEW

**Comment by LaszloLango** [comment]
@akosthekiss, I think there are more. Example: jrt-fatals.c

**Comment by zherczeg** [comment]
LGTM

**Comment by akosthekiss** [comment]
@LaszloLango are you sure you've checked it on current master? My tools cannot find any more.

**Comment by LaszloLango** [comment]
@akosthekiss, chekced version: f15e7be

**Comment by LaszloLango** [comment]
@akosthekiss, sorry. You are right. There are less of them on the current master. :) LGTM

**Comment by akosthekiss** [comment]
That's way too old :) #1239 removed the `(void)`-s from there. I got LGTM to that from a person I don't dare to name

**Pull request merged**
