### PR TITLE
Comment fixes which are left behind after the API update.

### PR DESCRIPTION
**Pull request by robertsipka**
JerryScript-DCO-1.0-Signed-off-by: Robert Sipka rsipka.uszeged@partner.samsung.com

### CODE REVIEW

**Comment by zherczeg** [comment]
Please also fix the documentation.

**Comment by robertsipka** [comment]
@zherczeg: I think the documentation is fine, these are missed when these were updated after the API changes.

**Comment by zherczeg** [comment]
Hm, these notes are not copied to the documentation. Fine then,
LGTM

**Comment by LaszloLango** [comment]
LGTM

**Comment by robertsipka** [comment]
Thanks,I've rebased it with master.

**Pull request merged**
