### PR TITLE
Fix EXTERNAL_LIBC_INTERFACE check with USE_COMPILER_DEFAULT_LIBC

### PR DESCRIPTION
**Pull request by seanshpark**
Related with #331

JerryScript-DCO-1.0-Signed-off-by: SaeHie Park saehie.park@samsung.com

### CODE REVIEW

**Comment by egavrin** [comment]
Cross build fails are not related to the PR.

**Comment by egavrin** [comment]
Good to me

**Comment by galpeter** [comment]
lgtm

**Comment by ruben-ayrapetyan** [comment]
@seanshpark, could you, please, describe the issue that is fixed by the changes?

**Comment by seanshpark** [comment]
Yes, 
What I understood is that, when 'USE_COMPILER_DEFAULT_LIBC' is 'YES' then 'EXTERNAL_LIBC_INTERFACE' should not be defined or if defined, value should be "UNDEFINED". if not, the both is defined by the caller and  I think should be treated as conflict.
With IoT.js, building for arm-linux with `USE_COMPILER_DEFAULT_LIBC` but without `EXTERNAL_LIBC_INTERFACE`, I get
```
CMake Error at CMakeLists.txt:98 (message):
  EXTERNAL_LIBC_INTERFACE='' should not be set in case compiler's default
  libc is used (USE_COMPILER_DEFAULT_LIBC=YES)
``` 
(line number 98 may not be the same)
So to solve this result is this PR

**Comment by ruben-ayrapetyan** [comment]
@seanshpark, thank you for detailed explanation of the issue.

**Comment by ruben-ayrapetyan** [comment]
Looks good to me

**Comment by egavrin** [comment]
`make push`

**Pull request merged**
