### PR TITLE
Fix documentation links in README.md

### PR DESCRIPTION
**Pull request by dmethvin**

### CODE REVIEW

**Comment by LaszloLango** [comment]
Please add DCO to the commit message:

> Signed-off-by message is incorrect. The following line should be at the end of the 2b41f07 commit's message: 'JerryScript-DCO-1.0-Signed-off-by: Dave Methvin dave.methvin@gmail.com'

**Comment by LaszloLango** [comment]
LGTM

**Comment by zherczeg** [comment]
LGTM

**Comment by LaszloLango** [comment]
@dmethvin, please rebase to the current master, so we can land the PR properly.

**Comment by dmethvin** [comment]
Done

**Pull request merged**
