### PR TITLE
Add missing RegExp case in the token_type_to_string

### PR DESCRIPTION
**Pull request by szledan**
JerryScript-DCO-1.0-Signed-off-by: Szilard Ledan szledan.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by szledan** [comment]
Fix for #284

**Comment by kkristof** [comment]
Looks good to me.

**Comment by LaszloLango** [comment]
Please add a test too.

**Comment by LaszloLango** [comment]
LGTM

**Comment by egavrin** [comment]
Good to me

**Comment by egavrin** [comment]
I'll push it

**Comment by egavrin** [comment]
Merged at d2457b1fc61c8eeced239662e9eede5752791dd8

**Pull request closed without merging**
