### PR TITLE
Update for Readme.md with link to Jerry page

### PR DESCRIPTION
**Pull request by Lopic**
JerryScript-DCO-1.0-Signed-off-by: Ilya Lopatin lopic19@gmail.com

### CODE REVIEW

**Comment by egavrin** [comment]
Please squash your commit, otherwise good to me.

**Comment by Lopic** [comment]
Is it good now?

**Comment by egavrin** [comment]
@Lopic much worse ^_^
```
+<<<<<<< HEAD
+You can find project details in [wiki](http://samsung.github.io/jerryscript/ "Jerry Script").
+=======
 You can find project details in wiki.		 You can find project details in wiki.
+>>>>>>> parent of fdccdb6... Updated Readme.md with link to original project
```

**Comment by egavrin** [comment]
Looks good.

**Comment by galpeter** [comment]
good for me also

**Comment by egavrin** [comment]
I'll push

**Comment by egavrin** [comment]
Merged as 6547cf3b2debfa91a8eb0e7d629dde7dbf389006

**Pull request closed without merging**
