### PR TITLE
Update the webpage

### PR DESCRIPTION
**Pull request by bzsolt**
JerryScript-DCO-1.0-Signed-off-by: Zsolt Borbély zsborbely.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by zherczeg** [comment]
LGTM

**Comment by LaszloLango** [comment]
Could you add #1313 to this PR?

**Comment by bzsolt** [comment]
Yes, thanks for the note.

**Comment by LaszloLango** [comment]
LGTM

**Pull request merged**
