### PR TITLE
Fix regexp character classes with \uNNNN and \xNN code points

### LINKED ISSUE #962: Incorrect regexp character class handling with \uNNNN and \xNN code points
Test code:
```js
function re_test (pattern, string)
{
  var r = new RegExp (pattern);
  print ("'" + pattern + "' ~ '" + string + "' => '" + (new RegExp (pattern)).exec(string) + "'");
}

re_test ("[\\u0020]", "u");
re_test ("[\\u0020]", " ");
re_test ("[\\u0020]", "x");

re_test ("[\\x20]", "u");
re_test ("[\\x20]", " ");
re_test ("[\\x20]", "x");
```

Output:
```
'[\u0020]' ~ 'u' => 'u'
'[\u0020]' ~ ' ' => ' '
'[\u0020]' ~ 'x' => 'null'
'[\x20]' ~ 'u' => 'null'
'[\x20]' ~ ' ' => ' '
'[\x20]' ~ 'x' => 'x'
```

The first and last results are incorrect.

This could either be fixed in #961 or handled separately (in which case a regtest could be added to the test suite as well, based on the above).

### PR DESCRIPTION
**Pull request by akiss77**
Also adding a regression test covering the issue.

Fixes #962

JerryScript-DCO-1.0-Signed-off-by: Akos Kiss akiss@inf.u-szeged.hu

### CODE REVIEW

**Comment by zherczeg** [comment]
What is the problem exactly?

**Comment by akiss77** [comment]
It's described in #962, as mentioned in the first comment. (In short: if a regexp contains a character class, and that character class contains a hex-specified code point -- either \uNNNN or \xNN --, then the current implementation incorrectly adds the character 'u' or 'x' to the character class as well.)

**Comment by zherczeg** [comment]
LGTM. I think in such cases it is better to describe the problem in the commit log as well.

**Comment by LaszloLango** [comment]
LGTM

**Pull request merged**
