### PR TITLE
Specialize fdlibm to jerry

### PR DESCRIPTION
**Pull request by akiss77**
Extensive rewrite of fdlibm. Please see commit comments for detailed description of the changes.

This change set gains 3K in code size on release ARM linux and 3.5K on release STM32F3,4 (debug mode experiences even higher reductions, 6-7K of code). Also, it shrinks the r/w data section even smaller.

On x86_64 linux, the benchmark results don't change: maxrss oscillates with +-4K, while running times changes also stay within the +-0.01 sec limits.

Detailed size results:
```
2027cae (authored on 2016-03-17 11:08:53 +0100, committed on 2016-03-22 08:05:00 +0100) [master] Performance optimizations
94f8cf8 (authored on 2016-03-13 22:30:47 +0100, committed on 2016-03-23 01:02:42 +0100) Specialize fdlibm to jerry
453dde6 (authored on 2016-03-16 19:01:31 +0100, committed on 2016-03-23 01:04:04 +0100) Turn simple constants to preprocessor macros
9a8128d (authored on 2016-03-16 21:05:00 +0100, committed on 2016-03-23 01:04:10 +0100) Merge sin/cos/tan and all helper functinos in a single source
af927c3 (authored on 2016-03-17 10:42:00 +0100, committed on 2016-03-23 01:04:20 +0100) Re-style fdlibm to conform to jerry guidelines
a351f91 (authored on 2016-03-20 14:32:05 +0100, committed on 2016-03-23 01:05:02 +0100) [fdlibm-spec] Fix asin

binary                                | data (202) | data (94f-453) | data (9a8-af9-a35) | diff | text (202) | text (94f) | diff | text (453) | diff | text (9a8-af9) | diff | text (a35) | diff |
--------------------------------------|------------|----------------|--------------------|------|------------|------------|------|------------|------|----------------|------|------------|------|
release.linux-arm7lhf                 |         24 |             20 |                 20 |    4 |     180086 |     178354 | 1732 |     177146 | 2940 |         177122 | 2964 |     177114 | 2972 |
release.linux-arm7lhf-cp              |         20 |             16 |                 16 |    4 |     132214 |     130573 | 1641 |     129373 | 2841 |         129325 | 2889 |     129317 | 2897 |
release.linux-arm7lhf-cp_minimal      |          0 |              0 |                  0 |      |      80749 |      80749 |      |      80749 |      |          80749 |      |      80749 |      |
release.linux-arm7lhf-mem_stats       |         24 |             17 |                 20 |    4 |     180734 |     179029 | 1705 |     177813 | 2921 |         177797 | 2937 |     177789 | 2945 |
release.linux-arm7lhf-mem_stress_test |         24 |             20 |                 20 |    4 |     180102 |     178369 | 1733 |     177161 | 2941 |         177147 | 2955 |     177133 | 2969 |
release.linux-x86_64                  |         24 |             17 |                 17 |    7 |     268097 |     265187 | 2910 |     263971 | 4126 |         264005 | 4092 |     264004 | 4093 |
release.linux-x86_64-cp               |         20 |             16 |                 16 |    4 |     203178 |     200254 | 2924 |     199080 | 4098 |         199163 | 4015 |     199162 | 4016 |
release.linux-x86_64-cp_minimal       |          0 |              0 |                  0 |      |     125837 |     125837 |      |     125837 |      |         125837 |      |     125837 |      |
release.linux-x86_64-mem_stats        |         24 |             17 |                 17 |    7 |     270188 |     267150 | 3038 |     265934 | 4254 |         265968 | 4220 |     265967 | 4221 |
release.linux-x86_64-mem_stress_test  |         24 |             17 |                 17 |    7 |     267721 |     264685 | 3036 |     263469 | 4252 |         263567 | 4154 |     263566 | 4155 |
release.mcu_stm32f3                   |         40 |             40 |                 40 |      |     186876 |     184556 | 2320 |     183356 | 3520 |         183364 | 3512 |     183356 | 3520 |
release.mcu_stm32f3-cp                |         40 |             36 |                 36 |    4 |     135388 |     133268 | 2120 |     132076 | 3312 |         132052 | 3336 |     132036 | 3352 |
release.mcu_stm32f3-cp_minimal        |         20 |             20 |                 20 |      |      75972 |      75972 |      |      75972 |      |          75972 |      |      75972 |      |
release.mcu_stm32f4                   |         40 |             40 |                 40 |      |     186876 |     184556 | 2320 |     183356 | 3520 |         183364 | 3512 |     183356 | 3520 |
release.mcu_stm32f4-cp                |         40 |             36 |                 36 |    4 |     135388 |     133268 | 2120 |     132076 | 3312 |         132052 | 3336 |     132036 | 3352 |
release.mcu_stm32f4-cp_minimal        |         20 |             20 |                 20 |      |      75972 |      75972 |      |      75972 |      |          75972 |      |      75972 |      |
debug.linux-arm7lhf                   |         32 |             28 |                 28 |    4 |     768828 |     764076 | 4752 |     762644 | 6184 |         762636 | 6192 |     762620 | 6208 |
debug.linux-arm7lhf-cp                |         28 |             24 |                 24 |    4 |     528880 |     525204 | 3676 |     523796 | 5084 |         523792 | 5088 |     523776 | 5104 |
debug.linux-arm7lhf-cp_minimal        |         24 |             24 |                 24 |      |     341756 |     341756 |      |     341756 |      |         341756 |      |     341756 |      |
debug.linux-arm7lhf-mem_stats         |         32 |             28 |                 28 |    4 |     771260 |     766508 | 4752 |     765076 | 6184 |         765068 | 6192 |     765052 | 6208 |
debug.linux-arm7lhf-mem_stress_test   |         32 |             28 |                 28 |    4 |     768900 |     764148 | 4752 |     762716 | 6184 |         762708 | 6192 |     762692 | 6208 |
debug.linux-x86_64                    |         52 |             48 |                 48 |    4 |     767906 |     761658 | 6248 |     760096 | 7810 |         760057 | 7849 |     760048 | 7858 |
debug.linux-x86_64-cp                 |         36 |             32 |                 32 |    4 |     586098 |     580697 | 5401 |     579153 | 6945 |         579114 | 6984 |     579105 | 6993 |
debug.linux-x86_64-cp_minimal         |         32 |             32 |                 32 |      |     393814 |     393814 |      |     393814 |      |         393814 |      |     393814 |      |
debug.linux-x86_64-mem_stats          |         52 |             48 |                 48 |    4 |     770893 |     764645 | 6248 |     763083 | 7810 |         763044 | 7849 |     763035 | 7858 |
debug.linux-x86_64-mem_stress_test    |         52 |             48 |                 48 |    4 |     767926 |     761678 | 6248 |     760116 | 7810 |         760077 | 7849 |     760068 | 7858 |
debug.mcu_stm32f4                     |         52 |             48 |                 48 |    4 |     784904 |     779744 | 5160 |     777864 | 7040 |         777864 | 7040 |     777856 | 7048 |
debug.mcu_stm32f4-cp                  |         48 |             44 |                 44 |    4 |     537732 |     532312 | 5420 |     530464 | 7268 |         530464 | 7268 |     530456 | 7276 |
debug.mcu_stm32f4-cp_minimal          |         44 |             44 |                 44 |      |     341000 |     341000 |      |     341000 |      |         341000 |      |     341000 |      |
```

This patch may be a first step towards transforming fdlibm into a jerry-libm. (Which, in addition to technical questions and decisions, may also require some license experts because of the copyright/licensing of fdlibm.)

### CODE REVIEW

**Comment by akiss77** [comment]
ping? r?

**Comment by LaszloLango** [comment]
Nice improvement, LGTM.

**Comment by zherczeg** [comment]
Does specialization means removing unnecessary functions?

**Comment by akiss77** [comment]
@zherczeg 
*Specialize fdlibm to jerry*

Keep IEEE code paths only:
* removed SVID, XOPEN, POSIX code paths from everywhere.
* deleted s_lib_version.c, as version is only useful if multiple
  standards are supported.
* deleted k_standard.c, as it handles non-IEEE exception cases only.
* renamed the e_{acos,asin,atan2,exp,fmod,log,pow,sqrt}.c sources as
  s_.*, dropped the __ieee754_ prefix from the names of the
  appropriate functions therein, and deleted the
  w_{acos,asin,atan2,exp,fmod,log,pow,sqrt}.c wrapper code.

Keep C99 declaration variants only:
* removed old C-style function declaration variants.
* removed data declaration variants where const qualifier was not
  used.

Clean unused sources/functions:
* removed s_{rint,significand,tanh}.c and the appropriate functions
  defined therein.

*Turn simple constants to preprocessor macros*

*Merge sin/cos/tan and all helper functinos in a single source*

* Made helper functions static.
* Changed the signature of __kernel_rem_pio2 not to require the
  ipio2 argument

*Re-style fdlibm to conform to jerry guidelines*

* First re-style was done automatically by indent to minimize the
  chance of errors during rewrite.

* Manual changes were applied to non-critical places only (comments
  and spaces):
  * Replaced all tabs with spaces.
  * Fixed tab stops in formulae in function comments.
    (Note: ASCII art for math formulae (especially for super- and
    subscripts) is a terrible idea.)
  * Unified the style of function comments.
  * Moved some in-code comments to their right places, which indent
    couldn't handle.
  * Added spaces to formulae of in-code comments to make them more
    readable.
  * Added braces mandated by jerry style guidelines.
  * Added parentheses to multiline #ifdef.

*Fix asin*

Re-styling of the sources revealed that the false branch of an
if-else construct in `asin` did not contain all the statements
that it should. (This was an issue -- a bad smell at least --
that's been around since 1995, according to the legacy SCCS ID.)

**Comment by zherczeg** [comment]
Thank you for the summary. I have been thinking about this direction for a while. The problem I see here is not technical, but a maintenance question: could we easily port all bugfixes from fdlibm to our version? An the other direction: if there is a bug in the code, do we understand it enough to fix it? Perhaps this is not a big risk, but I worry a bit. It would be good to discuss this before we land this.

**Comment by akiss77** [comment]
@zherczeg AFAIK the "authoritative" source for fdlibm is http://www.netlib.org/fdlibm/ . That site has the latest version (5.3), which is the very last official version for the lib, and that's what we started using in jerry. The last touch to the code was in 2004 (that's 12 yrs!) and I don't expect to happen anything to it anymore as Sun inc. is no more.

So, as there will be no more bugfixes in "upstream", porting them wont be an issue. And also because of this, if we find any bugs in the code in the future, we will have to understand and fix it on our own anyway.

**Comment by zherczeg** [comment]
Fair enough. LGTM

**Comment by akiss77** [comment]
Thanks for the reviews. One more thing: this time, I would *not* squash the patches, as that would make some not that closely related changes mixed together. OK/NOK? (Prefer the first :) )

**Comment by zherczeg** [comment]
Ok. But I would combine the 5th and 3rd together.

**Comment by LaszloLango** [comment]
@akiss77, OK, but please make sure that every commit pass on precommit!

**Pull request merged**
