### PR TITLE
Fix syntax checking for hex and regexp literals

### PR DESCRIPTION
**Pull request by sand1k**
This patch fixes the following tests form test262:
- ch07/7.8/7.8.3/S7.8.3_A6.1_T1.js
- ch07/7.8/7.8.3/S7.8.3_A6.1_T2.js
- ch07/7.8/7.8.5/S7.8.5_A1.5_T1.js
- ch07/7.8/7.8.5/S7.8.5_A1.5_T3.js
- ch07/7.8/7.8.5/S7.8.5_A2.5_T1.js
- ch07/7.8/7.8.5/S7.8.5_A2.5_T3.js

### CODE REVIEW

**Comment by ruben-ayrapetyan** [comment]
Looks good to me

**Comment by zherczeg** [comment]
LGTM

**Comment by egavrin** [comment]
`make push`

**Comment by sand1k** [comment]
Merged. Commits:
1195c19
f3ef9af

**Pull request closed without merging**
