### PR TITLE
Rename arduino_101 to zephyr

### PR DESCRIPTION
**Pull request by poussa**
The targets/arduino_101 is Zephyr port not specific to Arduino 101 board.
Other Zephyr boards can also be supported.
Make the directory and file naming reflect that.

JerryScript-DCO-1.0-Signed-off-by: Sakari Poussa sakari.poussa@intel.com

### CODE REVIEW

**Comment by poussa** [comment]
@sergioamr @grgustaf @pfalcon PTAL

**Comment by zherczeg** [comment]
How this is related to #1153 ?

**Comment by poussa** [comment]
@zherczeg sorry, did not see #1153. This is the same thing, so lets close this. Sorry for the noise.

**Comment by poussa** [comment]
Closing as a duplicate of #1153

**Comment by pfalcon** [comment]
@poussa : Sorry for the confusion, I'll make sure to cc: you on any related future pull requests. Also will make sure that any missing changes are included in my patch. Thanks!

**Pull request closed without merging**
