### PR TITLE
Fix lexing illegal exponential, Fix for issue #339

### PR DESCRIPTION
**Pull request by ILyoan**

### CODE REVIEW

**Comment by ruben-ayrapetyan** [comment]
@ILyoan, `lexer_parse_number` currently parses numbers in two phases:
 - determine type of number literal, at the same time checking for syntax correctness;
 - convert characters to number value.

`ecma_utf8_string_to_number` itself checks for correctness of number literal, so the code works correctly.
On the other hand, the function doesn't report what specifically is wrong in an incorrect number literal, so in the case we can't output message that would be more detailed than "invalid number literal".

Because of this, it seems better to check for correctness of exponent in the first phase, like the following:
```cpp
is_exp = true;
consume_char ();

if (LA (0) == LIT_CHAR_MINUS
    || LA (0) == LIT_CHAR_PLUS)
{
  consume_char ();
}

if (!lit_char_is_decimal_digit (LA (0)))
{
  PARSE_ERROR (JSP_EARLY_ERROR_SYNTAX,
               "Exponent mark in a numeric literal should be followed by a signed integer",
               lit_utf8_iterator_get_pos (&src_iter));
}
```

**Comment by ILyoan** [comment]
@ruben-ayrapetyan Ok, so any syntax checks should go into the first phase. It make sense. I'll update this PR.

**Comment by ILyoan** [comment]
@ruben-ayrapetyan Fixed it and rebased on top of master

**Comment by egavrin** [comment]
Fix commit message, please ^_^

```
Fix lexing of illegal exponential.

Related issue: #339

JerryScript-DCO-1.0-Signed-off-by: Ilyong Cho ily.cho@samsung.com
```

**Comment by ILyoan** [comment]
@egavrin Thanks, updated commit message.

**Comment by ruben-ayrapetyan** [comment]
Looks good to me

**Comment by galpeter** [comment]
lgtm

**Comment by egavrin** [comment]
`make push`

**Pull request merged**
