### PR TITLE
Turn off Date and RegExp built-in objects in compact profile

### PR DESCRIPTION
**Pull request by ruben-ayrapetyan**

### CODE REVIEW

**Comment by galpeter** [comment]
Typo: Turn **of** -> Turn **off** (in commit msg + title)

**Comment by egavrin** [comment]
Looks good.

**Comment by ruben-ayrapetyan** [comment]
@galpeter, thank you for the note.

**Comment by galpeter** [comment]
ahh yeah, and it looks good to me.

**Pull request merged**
