### PR TITLE
Fix: code-related vera++ rules should not be enforced in comments

### PR DESCRIPTION
**Pull request by akiss77**
JerryScript-DCO-1.0-Signed-off-by: Akos Kiss akiss@inf.u-szeged.hu

### CODE REVIEW

**Comment by zherczeg** [comment]
Thank you for fixing this. Could you add a test as well which proves that non-comments checks are not broken?

**Comment by akiss77** [comment]
AFAIK we have no automated testing facility for styles, do we? I've tried the following manually: before and after applying the patch, I've tweaked `main-mcu.c` (any other source file would have done it) and added the following lines:

```c
/* ( sigh *sigh* sigh ) */
char* p = NULL;
size_t s = sizeof (int );
```

Then I ran `make check-vera`. Without the patch, I got 4 errors (even within the comment), with the patch the remaining 2 errors come from code only, not from the comment. So, code is correctly checked still but comments are not checked anymore.

**Comment by zherczeg** [comment]
I see you updated the patch, but it seems a squash was done, so I don't see what issue turned up. Anyway, similar to the fdlibm unittests it would be good at some point to have some vera++ tests since now we have a lot of changes there. I worry that we accidentally broke the whole thing and no issues will be reported anymore. That can be done in another patch.

LGTM

**Comment by akiss77** [comment]
There was no issue, the patch has not been changed, just rebased to master, since it moved forward a bit since the pull request has been opened.

**Comment by LaszloLango** [comment]
LGTM

**Pull request merged**
