### PR TITLE
Fix assertion 'mem_pools == NULL' fail in JSON.stringify

### PR DESCRIPTION
**Pull request by rtakacs**
We should free values that are already in the collection.

### CODE REVIEW

**Comment by kkristof** [comment]
Could you add the test mentioned in #551?

**Comment by rtakacs** [comment]
I just modified an existing filtering test that reproduces the same issue. But yes, I can add the case that caused the assert.

**Comment by kkristof** [comment]
Looks good to me.

**Comment by zherczeg** [comment]
LGTM

**Comment by egavrin** [comment]
Good to me

**Comment by kkristof** [comment]
I'm going to land it.

**Comment by kkristof** [comment]
Landed in cc4283b94594201306831b44905bf0131238725e

**Pull request closed without merging**
