### PR TITLE
Remove recursion limit from RegExp engine.

### PR DESCRIPTION
**Pull request by LaszloLango**
JerryScript-DCO-1.0-Signed-off-by: László Langó llango.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by LaszloLango** [comment]
Related issue: #388

**Comment by egavrin** [comment]
Add `Related issue: #388` to commit message and this'd be good to me.

**Comment by LaszloLango** [comment]
@egavrin, commit message is fixed.

**Comment by ruben-ayrapetyan** [comment]
Looks good to me

**Comment by galpeter** [comment]
looks good to me

**Pull request merged**
