### PR TITLE
Fix Array.prototype.concat() argument array length.

### PR DESCRIPTION
**Pull request by dbatyai**
JerryScript-DCO-1.0-Signed-off-by: Dániel Bátyai dbatyai.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by egavrin** [comment]
Good to me

**Comment by galpeter** [comment]
lgtm

**Comment by egavrin** [comment]
I'll merge

**Comment by egavrin** [comment]
Merged at b414329ce83095bc3d6f483b72b6324df9f6ef2d

**Pull request closed without merging**
