### PR TITLE
Remove 'test-js-precommit' target from Makefile

### PR DESCRIPTION
**Pull request by LaszloLango**
When performing `make precommit`, instead of running only a subset of
the Jerry Test Suite on full profile builds, run the whole suite, and
also run the compact subset of the suite on compact builds. Also, make
CI perform the same tests.

Related issue: #879
Related PR: #912

JerryScript-DCO-1.0-Signed-off-by: László Langó llango.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by zherczeg** [comment]
LGTM

**Comment by akiss77** [comment]
This patch seems to make the whole "precommit" subset of the Jerry Test Suite superfluous. Then, there are more "leftovers" to remove:
* `JERRY_TEST_SUITE_JTS_PREC` is defined in `Makefile` (around line 150) and used as well (around line 310). Those are not necessary anymore.
* `tests/jerry-test-suite/precommit-test-list` also seems to be a candidate for removal.

**Comment by LaszloLango** [comment]
@akiss77, thanks for pointing out. I've updated the PR.

**Comment by akiss77** [comment]
LGTM

**Pull request merged**
