### PR TITLE
Fix the builtin Math.min and Math.max function

### PR DESCRIPTION
**Pull request by kkristof**
JerryScript-DCO-1.0-Signed-off-by: Kristof Kosztyo kkosztyo.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by kkristof** [comment]
If there are any `NaN` in the parameter list then the result always should be `NaN`.
It fixes two test262 test:
ch15/15.8/15.8.2/15.8.2.11/S15.8.2.11_A2
ch15/15.8/15.8.2/15.8.2.12/S15.8.2.12_A2

**Comment by galpeter** [comment]
lgtm

**Comment by ruben-ayrapetyan** [comment]
Looks good to me

**Comment by egavrin** [comment]
`make push`

**Pull request merged**
