### PR TITLE
Support local time output

### PR DESCRIPTION
**Pull request by rtakacs**

### CODE REVIEW

**Comment by kkristof** [comment]
Could you add test to the PR?

**Comment by rtakacs** [comment]
We cannot test the local time output, just now, while the TZA and DST are the same for everyone. If they are implemented, we should remove the these test cases.
Also added a test case for the Date object that constructed with an UTC time with a 'Z' suffix.

**Comment by kkristof** [comment]
Looks good to me.

**Comment by zherczeg** [comment]
LGTM

**Comment by egavrin** [comment]
Good to me. Rebase and `make push`

**Pull request merged**
