### PR TITLE
Fix syntax check for duplicate parameter names in a strict mode function

### PR DESCRIPTION
**Pull request by ruben-ayrapetyan**

### CODE REVIEW

**Comment by galpeter** [comment]
With this patch what happens if there is a code like this?
```js
function f(x,x) { return x; }
print(f(1,2));
```

If my memory serves right there is a testcase like this in the test262 and the result should be the 2nd argument.

**Comment by ruben-ayrapetyan** [comment]
@galpeter, the patch should not change behaviour of your test case.

Please, look at #273 pull request, that fixes behaviour of the test case.

**Comment by galpeter** [comment]
@ruben-ayrapetyan, okay, thanks for the info. 
lgtm

**Comment by egavrin** [comment]
@ruben-ayrapetyan please rebase it to master and I'll push it.

**Pull request merged**
