### PR TITLE
Optimize number literals.

### PR DESCRIPTION
**Pull request by LaszloLango**
JerryScript-DCO-1.0-Signed-off-by: László Langó llango.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by zherczeg** [comment]
Patch is good, but could it be measured on RPi2?

Also, please add an object literal regression test:
eval("({ get 1() {}, 1:1 })");

This should fail in ES5.1

**Comment by LaszloLango** [comment]
### RPi2's results ###

tools/run-perf-test.sh ./jerry_rel_91a0514_master ./jerry_rel_b328ff2_optimize_number_literals 10 600 ~/work/sunspider-1.0.23/ -m

Benchmark | RSS<br>(+ is better) | Perf<br>(+ is better)
---------: | --------- | ---------
3d-cube.js | `  96k ->   92k      `<br>`             +4.167%` | `  2.700s ->   2.690s                      `<br>`                 +0.370%  (+-0.943%) : [≈]`
access-binary-trees.js | `  84k ->   84k      `<br>`             +0.000%` | `  1.487s ->   1.508s                      `<br>`                 -1.457%  (+-1.245%) : [-]`
access-fannkuch.js | `  40k ->   40k      `<br>`             +0.000%` | `  8.020s ->   8.177s                      `<br>`                 -1.953%  (+-0.662%) : [-]`
access-nbody.js | `  48k ->   44k      `<br>`             +8.333%` | `  3.233s ->   3.260s                      `<br>`                 -0.825%  (+-0.769%) : [-]`
bitops-3bit-bits-in-byte.js | `  32k ->   32k      `<br>`             +0.000%` | `  1.758s ->   1.790s                      `<br>`                 -1.801%  (+-0.389%) : [-]`
bitops-bits-in-byte.js | `  32k ->   32k      `<br>`             +0.000%` | `  2.687s ->   2.723s                      `<br>`                 -1.365%  (+-0.451%) : [-]`
bitops-bitwise-and.js | `  28k ->   32k      `<br>`            -14.286%` | `  3.722s ->   3.750s                      `<br>`                 -0.761%  (+-0.653%) : [-]`
controlflow-recursive.js | ` 152k ->  148k      `<br>`             +2.632%` | `  0.900s ->   0.913s                      `<br>`                 -1.481%  (+-0.944%) : [-]`
crypto-aes.js | ` 124k ->  124k      `<br>`             +0.000%` | `  4.752s ->   4.765s                      `<br>`                 -0.281%  (+-0.855%) : [≈]`
crypto-md5.js | ` 184k ->  184k      `<br>`             +0.000%` | ` 21.152s ->  21.148s                      `<br>`                 +0.016%  (+-0.431%) : [≈]`
crypto-sha1.js | ` 132k ->  128k      `<br>`             +3.030%` | `  9.615s ->   9.630s                      `<br>`                 -0.156%  (+-0.992%) : [≈]`
date-format-tofte.js | `  64k ->   64k      `<br>`             +0.000%` | `  2.235s ->   2.225s                      `<br>`                 +0.447%  (+-0.734%) : [≈]`
date-format-xparb.js | `  64k ->   64k      `<br>`             +0.000%` | `  1.147s ->   1.145s                      `<br>`                 +0.146%  (+-1.080%) : [≈]`
math-cordic.js | `  32k ->   32k      `<br>`             +0.000%` | `  3.040s ->   3.105s                      `<br>`                 -2.138%  (+-1.076%) : [-]`
math-partial-sums.js | `  36k ->   36k      `<br>`             +0.000%` | `  1.857s ->   1.853s                      `<br>`                 +0.180%  (+-0.856%) : [≈]`
math-spectral-norm.js | `  44k ->   40k      `<br>`             +9.091%` | `  1.538s ->   1.530s                      `<br>`                 +0.541%  (+-0.434%) : [+]`
string-fasta.js | `  48k ->   48k      `<br>`             +0.000%` | `  4.617s ->   4.657s                      `<br>`                 -0.866%  (+-0.471%) : [-]`
Geometric mean: | RSS reduction: `0.871%` | Speed up: `-0.666% (+-0.194%) : [-]`

**Comment by zherczeg** [comment]
Technically it is just noise. LGTM

**Comment by zherczeg** [comment]
(after the test case is added of course, this patch is also a bugfix)

**Comment by LaszloLango** [comment]
@zherczeg, I've updeted the PR. The mentioned new test case was added.

**Pull request merged**
