### PR TITLE
Add ARM cross build and QEMU user space emulated tests to the CI

### PR DESCRIPTION
**Pull request by akiss77**
JerryScript-DCO-1.0-Signed-off-by: Akos Kiss akiss@inf.u-szeged.hu

### CODE REVIEW

**Comment by akiss77** [comment]
Travis CI has no ARM devices to deploy and test the project on, but we could have QEMU user space emulation running. This way cross building for ARM and emulated execution of ARM code could be tested for every PR and push. Builds are of the same speed, tests are somewhat slower (but still not that bad). Opinions?

**Comment by zherczeg** [comment]
Can you install something on Travis?

**Comment by akiss77** [comment]
Please, _do_ have a look at the `.travis.yml` file... (And `tools/apt-get-install-*.sh`.) They are among the changed files of this very PR. That's how dependences are already installed (e.g., gcc-arm-none-eabi, cppcheck, vera++, etc.).

The question is not whether we can do it (yes, we can) but whether we want it?

**Comment by LaszloLango** [comment]
I'd like this feature. +1

**Comment by zherczeg** [comment]
If it does not slow down the CI too much, it is ok for me.

**Comment by zherczeg** [comment]
Akos, do you plan to land this patch?

**Comment by akiss77** [comment]
@zherczeg I'd like to, but on current master, we have 5 failures on arm/linux. This would turn all PRs and even the master red, so I'd keep this PR open until the failures are fixed. I'll open an issue for the problem.

**Comment by LaszloLango** [comment]
@akiss77, @zherczeg please check #929

**Comment by akiss77** [comment]
The patch has been rebased. All blocker issues have been solved, so I think we are ready to re-introduce arm builds and emulate arm tests. 
@LaszloLango @zherczeg r?

**Comment by LaszloLango** [comment]
LGTM

**Comment by zherczeg** [comment]
LGTM

**Pull request merged**
