### PR TITLE
Fix assertion fail in ecma_date_make_day

### PR DESCRIPTION
**Pull request by szledan**
JerryScript-DCO-1.0-Signed-off-by: Szilard Ledan szledan.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by ruben-ayrapetyan** [comment]
@szledan, the following test loops infinitely in `ecma_date_time_from_year`:
```
new Date(-2, -2).getFullYear()
```
Maybe, it is not related to the pull request. Could you, please, check this?

**Comment by ruben-ayrapetyan** [comment]
@szledan, now the `new Date(-2, -2).getFullYear()` test case doesn't lead to infinite loop. Thank you for update.

**Comment by ruben-ayrapetyan** [comment]
Looks good to me

**Comment by kkristof** [comment]
Looks good to me.

**Comment by LaszloLango** [comment]
Merged: 7c1622855da1c4757d9c76c3bcdac3e47408ed76 & 9edae36b0053a976f679568dc12d78de2207f363

**Pull request closed without merging**
