### PR TITLE
Remove comparison of unused instruction operands fields (the fields could be uninitialized)

### PR DESCRIPTION
**Pull request by ruben-ayrapetyan**
Related issue: #585

### CODE REVIEW

**Comment by seanshpark** [comment]
Good, #585 is fixed with this.

**Comment by ruben-ayrapetyan** [comment]
@seanshpark, thank you!

**Comment by egavrin** [comment]
good to me

**Comment by zherczeg** [comment]
LGTM. What is the effect on the binary size?

**Comment by ruben-ayrapetyan** [comment]
@zherczeg, the change is only in a unit test, so it doesn't influence binary size of the engine's core.

**Pull request merged**
