### PR TITLE
Cross-build fix after 5e301a1d71a23e8141c4427ae2444c223a1c4c42

### PR DESCRIPTION
**Pull request by zherczeg**
JerryScript-DCO-1.0-Signed-off-by: Zoltan Herczeg zherczeg@inf.u-szeged.hu

### CODE REVIEW

**Comment by egavrin** [comment]
Let's check is build if OK, and `make push`

**Comment by zherczeg** [comment]
Why this patch is not checked by Jenkins?

**Comment by ruben-ayrapetyan** [comment]
@zherczeg, seems that Jenkins was busy with testing another pull requests (#580 and #581), and now it started to check this patch.

**Comment by zherczeg** [comment]
Seems it likes it

**Comment by zherczeg** [comment]
Shall I land it?

**Comment by egavrin** [comment]
Land it, please.

**Comment by zherczeg** [comment]
Landed in 4dcbdb44ff7ce3d8c40d98b9a405710a9fd76fc6

**Pull request closed without merging**
