### PR TITLE
Updated Zephyr command line shell after API changes

### PR DESCRIPTION
**Pull request by jimmy-huang**
JerryScript-DCO-1.0-Signed-off-by: Jimmy Huang jimmy.huang@intel.com

### CODE REVIEW

**Comment by LaszloLango** [comment]
LGTM

**Comment by zherczeg** [comment]
LGTM

**Comment by bzsolt** [comment]
@jimmy-huang, please rebase to the current master, and I will merge it.

**Comment by jimmy-huang** [comment]
@bzsolt rebased

**Pull request merged**
