### PR TITLE
Implement prerequisites auto-update and switch to cppcheck v1.69

### PR DESCRIPTION
**Pull request by ruben-ayrapetyan**
Updating to cppcheck v1.69, as v1.66 loops infinitely on PR #595.

### CODE REVIEW

**Comment by egavrin** [comment]
Please, add support of versionning for prerequisites. In that case, preqs will be updated automatically.

**Comment by ruben-ayrapetyan** [comment]
@egavrin, done.

**Comment by zherczeg** [comment]
Looks good to me

**Comment by zherczeg** [comment]
Actually I like the brackets around the & operation, cleaner syntax

**Comment by egavrin** [comment]
Split on three commits, please:

- Fix of *.cpp files
- Add auto-updater
- New version of cppcheck

**Comment by ruben-ayrapetyan** [comment]
@egavrin, done.

**Comment by egavrin** [comment]
Great, LGTM

**Pull request merged**
