### PR TITLE
Compact Byte Code parser and executor for Jerry (release branch).

### PR DESCRIPTION
**Pull request by zherczeg**
Compact Byte Code parser and executor for Jerry.

JerryScript-DCO-1.0-Signed-off-by: Zoltan Herczeg zherczeg@inf.u-szeged.hu
JerryScript-DCO-1.0-Signed-off-by: László Langó llango.u-szeged@partner.samsung.com
JerryScript-DCO-1.0-Signed-off-by: Tamas Gergely tgergely.u-szeged@partner.samsung.com
JerryScript-DCO-1.0-Signed-off-by: Zsolt Borbély zsborbely.u-szeged@partner.samsung.com
JerryScript-DCO-1.0-Signed-off-by: Roland Takacs rtakacs.u-szeged@partner.samsung.com
JerryScript-DCO-1.0-Signed-off-by: István Kádár ikadar@inf.u-szeged.hu

### CODE REVIEW

**Comment by zherczeg** [comment]
Hi all,

this pull request contains the release branch of a Compact Byte Code (CBC) parser and executor of Jerry. The short summary is we achieved progress on all aspects of Jerry, including memory consumption, performance and binary size.

The bad news is that the patch is huge, but the good news we don't need to fix everything before landing it. It is enough to focus on the style issues. The rest can be done in followup patches. The biggest problem is loosing the change log after squashing, and this makes tracking bugs quite difficult.

In the followings we show the results of the CBC work.

Full Test262 conformance in debug mode with 30s timeout (in debug some tests runs several minutes, they would pass, but excluded now).

=== Summary ===
 - Ran 11725 tests
 - Passed 11332 tests (96.6%)
 - Failed 393 tests (3.4%)

This shows that the CBC engine is stable, and there is no risk of moving to CBC. Of course the remaining issues will be fixed in (much) smaller commits.

Binary size:

* Current master binary size: 202436 bytes
* CBC binary size: 183648 bytes
* Gain: 9.2%

Parsing results of the concatenation of IoT.js on Raspberry Pi 2:

Current master:

* Heap stats:
  Heap size = 260096 bytes
  Chunk size = 64 bytes
  Allocated chunks count = 0
  Allocated = 0 bytes
  Waste = 0 bytes
  Peak allocated chunks count = 1322
  Peak allocated = 76540 bytes
  Peak waste = 10436 bytes

* Runtime: 0.84 sec

CBC Parser:

Heap stats:
  Heap size = 260096 bytes
  Chunk size = 64 bytes
  Allocated chunks count = 0
  Allocated = 0 bytes
  Waste = 0 bytes
  Peak allocated chunks count = 793
  Peak allocated = 41337 bytes
  Peak waste = 9451 bytes

  Note: Total byte code size is 12650 bytes

* Runtime: 0.14 sec

Gain:

* Memory: 46% memory reduction
* Runtime: 6 times faster

SunSpider results:

|                               Benchmark |         RSS<br>(+ is better) |        Perf<br>(+ is better) |
|                               --------- |                          --- |                         ---- |
|                              3d-cube.js |         112->    88 (21.429) |       3.166-> 2.771 (12.476) |
|                  access-binary-trees.js |           84->    80 (4.762) |       1.854-> 1.584 (14.563) |
|                      access-fannkuch.js |          40->    36 (10.000) |       9.169-> 7.946 (13.338) |
|                         access-nbody.js |          48->    40 (16.667) |       4.229->  3.26 (22.913) |
|             bitops-3bit-bits-in-byte.js |          32->    24 (25.000) |       2.326-> 1.906 (18.057) |
|                  bitops-bits-in-byte.js |          32->    24 (25.000) |        3.117-> 2.871 (7.892) |
|                   bitops-bitwise-and.js |          32->    24 (25.000) |      3.575-> 3.971 (-11.077) |
|                controlflow-recursive.js |         220->   136 (38.182) |       1.589-> 1.052 (33.795) |
|                           crypto-aes.js |          128->   116 (9.375) |        5.248-> 4.797 (8.594) |
|                           crypto-md5.js |          184->   180 (2.174) |        22.17->21.632 (2.427) |
|                          crypto-sha1.js |          132->   124 (6.061) |       10.417-> 9.721 (6.681) |
|                    date-format-tofte.js |          72->    60 (16.667) |       3.342-> 2.334 (30.162) |
|                    date-format-xparb.js |          72->    60 (16.667) |       1.749-> 1.235 (29.388) |
|                          math-cordic.js |          40->    28 (30.000) |        3.349->  3.17 (5.345) |
|                    math-partial-sums.js |          32->    28 (12.500) |        1.999-> 1.963 (1.801) |
|                   math-spectral-norm.js |          40->    32 (20.000) |       2.158-> 1.616 (25.116) |
|                         string-fasta.js |           48->    44 (8.333) |       5.596-> 4.613 (17.566) |
|                         Geometric mean: |      RSS reduction: 17.4965% |           Speed up: 14.8297% |

Only the runtime of one test is decreased, but everything else is improved. There are several tests with 25+ % memory or performance improvement. We did not focus on SunSpider results, it seems this is the effect of using a simpler design.

I think we achieved more than we initially expected. The key advantage of Compct Byte Code is combining simplicity and efficiency, and this is proved by reducing both memory and binary size, and improved performance. 

Please review the patch and help us with feedback. Lets land this work soon and continue the development on the master branch.

**Comment by seanshpark** [comment]
:+1:

**Comment by lemmaa** [comment]
Great! hope to be landing well shortly! :)

**Comment by zherczeg** [comment]
@huxinx if you have some time, could you measure this patch on intel?

**Comment by huxinx** [comment]
There are build errors on X86. I just did a rough fix to make compiling pass.

https://github.com/Samsung/jerryscript/compare/cbc_integration_dev_release...huxinx:cbc_integration_dev_release

Run ./tools/run-perf-test.sh 10 times, 
OS, ubuntu 15.04, 32 bit
CPU, Intel(R) Celeron(R) CPU N2820 @ 2.13GHz, 2 core

                              Benchmark |         RSS<br>(+ is better) |        Perf<br>(+ is better) |
                               --------- |                          --- |                         ---- |
                              3d-cube.js |          116->   116 (0.000) |     1.06933->1.06756 (0.166) |3d-morph.js | <FAILED>3d-raytrace.js | <FAILED>
                  access-binary-trees.js |           84->    84 (0.000) |   0.653778->0.647556 (0.952) |
                      access-fannkuch.js |          44->    36 (18.182) |    3.46133->3.47822 (-0.488) |access-nbody.js | <FAILED>access-nsieve.js | <FAILED>
             bitops-3bit-bits-in-byte.js |           36->    36 (0.000) |   0.903111->0.892889 (1.132) |
                  bitops-bits-in-byte.js |         36->    40 (-11.111) |       1.18->1.19689 (-1.431) |
                   bitops-bitwise-and.js |          40->    28 (30.000) |    1.22044->1.23867 (-1.494) |
                   bitops-nsieve-bits.js |          160->   160 (0.000) |      10.02->10.0333 (-0.133) |
                controlflow-recursive.js |          244->   244 (0.000) |  0.552444->0.556444 (-0.724) |
                           crypto-aes.js |          132->   132 (0.000) |     2.07156-> 2.072 (-0.021) |
                           crypto-md5.js |          192->   188 (2.083) |     10.6004->10.5982 (0.021) |
                          crypto-sha1.js |          140->   140 (0.000) |    4.80089->4.80311 (-0.046) |
                    date-format-tofte.js |           80->    80 (0.000) |     1.18889->1.18622 (0.225) |
                    date-format-xparb.js |           76->    76 (0.000) |   0.638222->0.630222 (1.253) |
                          math-cordic.js |           44->    40 (9.091) |    1.28533->1.29733 (-0.934) |math-partial-sums.js | <FAILED>
                   math-spectral-norm.js |           44->    44 (0.000) |   0.788889->0.784889 (0.507) |regexp-dna.js | <FAILED>
                         string-fasta.js |          56->    48 (14.286) |     2.14978->2.13778 (0.558) |string-tagcloud.js | <FAILED>string-unpack-code.js | <FAILED>string-validate-input.js | <FAILED>
                         Geometric mean: |       RSS reduction: 4.4152% |            Speed up: -0.025% |
Fri Jan 22 10:35:58 EST 2016


Binary size:
Current master binary size: 292k
CBC binary size: 272k

**Comment by zherczeg** [comment]
The numbers are too similar in the two columns. Are you sure you run the two different binaries?

**Comment by zherczeg** [comment]
And please measure them on the edison board.

**Comment by jiangzidong** [comment]
on Edison Board

                               Benchmark |         RSS<br>(+ is better) |        Perf<br>(+ is better) |
                               --------- |                          --- |                         ---- |
                              3d-cube.js |         112->    76 (32.143) |       5.16->4.18333 (18.928) |
                  access-binary-trees.js |          84->    64 (23.810) |    3.13667->2.38333 (24.017) |
                      access-fannkuch.js |          40->    20 (50.000) |    16.5833->13.5733 (18.151) |
             bitops-3bit-bits-in-byte.js |          28->    16 (42.857) |        4.3->3.23333 (24.806) |
                  bitops-bits-in-byte.js |          28->    16 (42.857) |    5.73333->4.81333 (16.046) |
                   bitops-bitwise-and.js |          32->    16 (50.000) |    5.94667->6.14667 (-3.363) |
                controlflow-recursive.js |         240->   132 (45.000) |     2.71667->   1.5 (44.785) |
                           crypto-aes.js |         128->   108 (15.625) |     10.0167->  8.51 (15.042) |
                           crypto-md5.js |         188->   168 (10.638) |     50.9033->50.0267 (1.722) |
                          crypto-sha1.js |         132->   116 (12.121) |       23.06->22.0933 (4.192) |
                    date-format-tofte.js |          76->    52 (31.579) |    5.73333->3.70333 (35.407) |
                    date-format-xparb.js |          72->    56 (22.222) |     3.05667->  1.98 (35.224) |
                          math-cordic.js |          36->    24 (33.333) |    6.13667->5.30333 (13.580) |
                   math-spectral-norm.js |          40->    24 (40.000) |    3.77667->2.54667 (32.568) |
                         string-fasta.js | <FAILED>|<FAILED>|
                         Geometric mean: |      RSS reduction: 33.5484% |           Speed up: 21.2257% |

* the original run-perf-test cannot run on edison, because 1) the sleep in busybox don't support float argument, I use usleep instead. 2) the `timeout` command is not included in the yoctoOS, So don't use the `timeout`

* in Edison and my x86 host, the  `string-fasta.js` failed after the patch

**Comment by huxinx** [comment]
Update SunSpider results on NUC. @zherczeg

**Comment by zherczeg** [comment]
Thank you very much!

**Comment by zherczeg** [comment]
Regarding failures, this patch is quite big (1.3Mb at the moment), so it will likely cause breaks. We will fix these issues. Perhaps not everything in this huge patch, but in follow-up patches. Anyway, we just achieved 98.1% test262 conformance in debug mode, and preparing a new release patch soon.

**Comment by zherczeg** [comment]
Release patch is done. Latest results on RPi2:

                               Benchmark |         RSS<br>(+ is better) |        Perf<br>(+ is better) |
                               --------- |                          --- |                         ---- |
                              3d-cube.js |         108->    88 (18.518) |       4.339->   3.8 (12.422) | 
                  access-binary-trees.js |           84->    76 (9.524) |       2.543-> 2.189 (13.921) | 
                      access-fannkuch.js |          40->    32 (20.000) |      12.024->10.302 (14.321) | 
                         access-nbody.js |          44->    36 (18.182) |       5.164-> 4.348 (15.802) | 
             bitops-3bit-bits-in-byte.js |          36->    24 (33.333) |       2.714-> 2.437 (10.206) | 
                  bitops-bits-in-byte.js |          36->    24 (33.333) |       3.649-> 3.136 (14.059) | 
                   bitops-bitwise-and.js |          36->    16 (55.556) |        4.503-> 4.409 (2.087) | 
                controlflow-recursive.js |         228->   140 (38.596) |        1.76-> 1.233 (29.943) | 
                           crypto-aes.js |         132->   112 (15.152) |       5.673-> 5.094 (10.206) | 
                           crypto-md5.js |          192->   176 (8.333) |      26.151->26.401 (-0.956) | 
                          crypto-sha1.js |          132->   124 (6.061) |       11.355->11.198 (1.383) | 
                    date-format-tofte.js |          76->    56 (26.316) |       3.952-> 2.711 (31.402) | 
                    date-format-xparb.js |          72->    56 (22.222) |       2.297-> 1.543 (32.825) | 
                          math-cordic.js |          40->    24 (40.000) |       3.974-> 4.173 (-5.008) | 
                    math-partial-sums.js |          36->    28 (22.222) |        2.602-> 2.511 (3.497) | 
                   math-spectral-norm.js |          44->    32 (27.273) |        2.69-> 2.235 (16.915) | 
                         string-fasta.js |          48->    40 (16.667) |       7.214-> 5.987 (17.009) | 
                         Geometric mean: |       RSS reduction: 25.357% |           Speed up: 13.6276% |

**Comment by sand1k** [comment]
@zherczeg, good job!

We have several questions:
1. Is snapshot supported by this patch? This is important feature, which should be working.
2. Could you please update the PR, so that original jerry's bytecode would be available? I think we should add a build-time flag, indicating which bytecode to use.

**Comment by zherczeg** [comment]
Hi,
1) We have no snapshot support, and I think the patch is big enough :( We can add it (and many other things) later in smaller patches.
2) If somebody needs this, we can add it later as well.

**Comment by akiss77** [comment]
I'd argue against keeping both implementations in the code base. That would give only a little advantage over keeping the two implementations in branches/forks but will be a hell to maintain, and will certainly not point toward a best unified solution. I'm much concerned that the two byte code approaches will keep living their own more and more divergent life.

**Comment by zherczeg** [comment]
Sry, accidentally closing this.

**Comment by tilmannOSG** [comment]
I strongly agree with @akiss77  and share his concerns. I don't think it makes sense to have two different byte code implementations in the tree.

@sand1k @egavrin @ruben-ayrapetyan In the last IoT.js/JerryScript workshop all parties agreed that if the compact byte code turns out to be a significant improvement it will replace the existing implementation. Those goals have been met so we should proceed accordingly.

Making both byte code implementations coexist is a significant amount of effort with no perceived gain. This effort is better spent on improving JerryScript.

The snapshot support is an important feature but it should not block the merge of the compact byte code. The current patch is big enough as it is and as there are no (known) use cases where the lack of snapshotting causes a regression (the overall benefit of snapshotting is also reduced due to the increased efficiency of the compact byte code implementation).

@lemmaa , you seem to be very keen on getting the compact byte code merged, what is your perspective on this?

**Comment by lemmaa** [comment]
@tilmannOSG I really want to land this patch ASAP. At the same time, I also think that we would better to keep both implementations, at least for a while. Because we need to have enough time to investigate CBC implementations from every perspective. __So, how about keep both implementations until next workshop and do investigation and improvement?__ One big problem in this approach is I can't find what is efficient way to keep the both. Build time configuration looks too complex to make patch, and keep in separate branch also in maintenance. 

From the other point of view, I think we need to consider making followings completed before landing.
* same Test-262 pass rate to current BC.
* snapshot support.
* compact profile support (I can't sure is it already considered or not)
 
As for snapshot, CBC reduces footprint of byte code very big, but main purpose of snapshot is not reducing the footprint of byte code but moving byte code storage to FLASH from RAM. So It need to be implemented even CBC landed. One more, the effect of snapshot is much higher in large framework codes, like `IoT.js`, than small benchmark code. Yes, `IoT.js` is actual use case of snapshot. :)

@zherczeg, @egavrin Do you have good idea to keep both implementations?

**Comment by akiss77** [comment]
@lemmaa AFAIK
* test262 pass rate is better with CBC (with no regressions);
* snapshot support is already implemented in the development branch (and this PR will get updated to incorporate that enhancement - together with various others); and 
* the same holds for compact profile support.

@zherczeg can confirm the above (and give an estimation when the next PR update from the dev branch is planned to happen)

**Comment by zherczeg** [comment]
tests-262, jerry-release:
* current Jerry master: 20 failures (excluding intl)
* current cbc dev branch: 12 failures (excluding intl)

The 12 failures are also part of the 20, so new failures introduced.

* We finished the snapshot support yesterday. Today we run SunSpider to check whether it works. It worked.

* We also added compact profile because it is tested by "make precommit".

The difficulty for having multiple implementations in one trunk:
- Header names (same name: conflict, different name: duplicates includes)
- Testing (maintenance)
- New features requires double implementation

I fully understand the risk of moving to a new implementation. The question is whether all my tools will work? Please try them and we will fix the issues you encounter in a short time. I think maintaining two implementations is much more resource consuming than fixing the issues. We can also check out the current byte code from git if we need it in the future.

For example, we have already been aware that one line needs to be changed in IoT.js for cbc: there is no need to include the zero terminator for strings passed to jerry_eval (zero is not a valid JavaScript character, and CBC correctly throws a syntax error). After that change, all IoT.js tests are passed. But you might encounter other issues as well. Perhaps we should open an IoT.js branch for cbc, and collect such fixes there.

**Comment by zherczeg** [comment]
New commit with snapshot support. "make precommit" runs cleanly. Please try it and let us know if something does not work.

**Comment by tilmannOSG** [comment]
Yes, as mentioned before, having two byte code implementations in the tree is an absolute maintenance nightmare. This is not a practical way to move forward. JerryScript is a small project and we need to be careful to spend our limited resources on efforts which add significant value to the project.

As @zherczeg said, there's always a risk in moving to a new implementation. However, our current results indicate that the compact byte code implementation is a **strict improvement both in correctness and performance**. In addition, the authors of this patch already have a track record of addressing any identified issues quickly. Moving to the new byte code implementation is also fully transparent to the users.

This pull request has been open for one and a half weeks now and to my knowledge there was not a single issue reported.

Everyone who has concerns about this patch please test it with your code and report any issues you found.

@huxinx If you could test the new implementation with your own use cases we would highly appreciate any feedback :)

I propose that we allow for another week of testing and assuming no blocking issues are found we proceed with the merge.

**Comment by lemmaa** [comment]
@akiss77 @zherczeg Thanks for explanation, it looks like all issues cleared for me. :) Today, @wateret added `cbc_integration_dev` to daily benchmark graph of http://samsung.github.io/jerryscript/benchmark/benchmark.html?show=sum for reference.

@egavrin We need you opinion about this, please.

**Comment by zherczeg** [comment]
Thank you @lemmaa. Progress is visible on those charts as well.

**Comment by zherczeg** [comment]
We tried IoT.js with snapshot. It works after the following two changes:

* Land https://github.com/Samsung/jerryscript/pull/824 (IoT.js does not compile with the latest Jerry).
* In iotjs_module_process.cpp, the +1 after 'String code("", len1 + len2 + len3 + 1);' needs to be removed. The String automatically allocates memory for the terminator zero value.

Both changes are unrelated to CBC.

**Comment by huxinx** [comment]
Latest results on NUC.
 
OS, ubuntu 15.04, 32 bit
CPU, Intel(R) Celeron(R) CPU N2820 @ 2.13GHz, 2 core

                               Benchmark |         RSS<br>(+ is better) |        Perf<br>(+ is better) |
                               --------- |                          --- |                         ---- |
                              3d-cube.js |         120->    92 (23.333) |   1.06933->0.878222 (17.872) |3d-morph.js | <FAILED>3d-raytrace.js | <FAILED>
                  access-binary-trees.js |          88->    76 (13.636) |  0.653333->0.500889 (23.333) |
                      access-fannkuch.js |          44->    36 (18.182) |    3.46133->2.87778 (16.859) |access-nbody.js | <FAILED>access-nsieve.js | <FAILED>
             bitops-3bit-bits-in-byte.js |          32->    28 (12.500) |  0.901333->0.651111 (27.761) |
                  bitops-bits-in-byte.js |          36->    28 (22.222) |   1.17778->0.967111 (17.887) |
                   bitops-bitwise-and.js |          36->    20 (44.444) |       1.22->1.29556 (-6.193) |
                   bitops-nsieve-bits.js |          156->   148 (5.128) |    10.0191->10.1031 (-0.838) |
                controlflow-recursive.js |         244->   140 (42.623) |     0.552->0.295556 (46.457) |
                           crypto-aes.js |         132->   116 (12.121) |    2.06667->1.83022 (11.441) |
                           crypto-md5.js |          192->   180 (6.250) |     10.5973->10.4102 (1.765) |
                          crypto-sha1.js |          136->   132 (2.941) |     4.80444->4.59733 (4.311) |
                    date-format-tofte.js |          80->    68 (15.000) |   1.18844->0.796889 (32.947) |
                    date-format-xparb.js |          80->    60 (25.000) |  0.637333->0.419556 (34.170) |
                          math-cordic.js |          40->    28 (30.000) |    1.28578->1.08844 (15.348) |math-partial-sums.js | <FAILED>
                   math-spectral-norm.js |          44->    32 (27.273) |    0.790667->  0.52 (34.233) |regexp-dna.js | <FAILED>
                         string-fasta.js |          56->    44 (21.429) |     2.15067-> 1.804 (16.119) |string-tagcloud.js | <FAILED>string-unpack-code.js | <FAILED>string-validate-input.js | <FAILED>
                         Geometric mean: |      RSS reduction: 21.0608% |           Speed up: 19.5892% |
Tue Feb  2 06:29:51 EST 2016

**Comment by zherczeg** [comment]
Thank you for the measurement. I suppose that means the compilation issues you encountered before were fixed.

I hope @sand1k @egavrin @ruben-ayrapetyan give their positive feedback soon and we can land this four month of work. I am not aware of anything else that blocks the landing process.

**Comment by zherczeg** [comment]
Since no serious issues has been reported, we would like to land this patch tomorrow. If anybody encounters any bugs please report them and we will fix them. Please report only the bugs. I am aware that in a 40000 lines of patch there is a lot of opportunity to refactor certain parts, but that would delay the landing of this major advancement. Of course we can (should!) refactor those parts in smaller patches later.

**Comment by zherczeg** [comment]
Landed in https://github.com/Samsung/jerryscript/commit/4d2dd22ced5ce311530506405aea61c1f32181f6
Thank you for all help and feedback.

**Pull request closed without merging**
