### PR TITLE
Mimic the test-262 expected behaviour in string.replace

### PR DESCRIPTION
**Pull request by zherczeg**
JerryScript-DCO-1.0-Signed-off-by: Zoltan Herczeg zherczeg@inf.u-szeged.hu

### CODE REVIEW

**Comment by ruben-ayrapetyan** [comment]
@zherczeg, could you, please, add comment to implementation-defined part with details about current behaviour of the part?

**Comment by zherczeg** [comment]
Yes, explanation added.

**Comment by ruben-ayrapetyan** [comment]
Looks good to me

**Comment by kkristof** [comment]
Looks good to me.

**Comment by zherczeg** [comment]
Landed in a751478a199ad30ff74b0163fbc435cc7b0cff34

**Pull request closed without merging**
