### PR TITLE
Test lastIndex calculation for exec calls

### PR DESCRIPTION
**Pull request by galpeter**
JerryScript-DCO-1.0-Signed-off-by: Peter Gal pgal.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by LaszloLango** [comment]
LGTM

**Comment by galpeter** [comment]
Rebased to master and now we only need the tests.

**Comment by egavrin** [comment]
@galpeter seams on test is added, is it true?

**Comment by galpeter** [comment]
@egavrin, yes, only tests were added, as the code fix part was also fixed in the regexp unicode branch which already landed making the code fixes in this PR irrelevant.

**Comment by egavrin** [comment]
@galpeter I see.

`make push`

**Pull request merged**
