### PR TITLE
Remove `main-darwin.cpp` for easy maintenance.

### PR DESCRIPTION
**Pull request by lemmaa**
JerryScript-DCO-1.0-Signed-off-by: Sung-Jae Lee sjlee@mail.com

### CODE REVIEW

**Comment by LaszloLango** [comment]
LGTM

**Comment by seanshpark** [comment]
how about rename `main-linux.cpp` to  `main-unix.cpp`? since its for both.

**Comment by LaszloLango** [comment]
@seanshpark, I have no problem with renaming the file to `main-unix.cpp`.

**Comment by egavrin** [comment]
LGTM

**Comment by lemmaa** [comment]
@seanshpark @LaszloLango Changed file-name to `main-unix.cpp` and merged.

**Comment by LaszloLango** [comment]
The patch still looks good to me.

**Pull request merged**
