### PR TITLE
Fix build break on OSX: Invalid type comparision.

### PR DESCRIPTION
**Pull request by lemmaa**
JerryScript-DCO-1.0-Signed-off-by: Sung-Jae Lee sjlee@mail.com

### CODE REVIEW

**Comment by zherczeg** [comment]
LGTM

**Comment by lemmaa** [comment]
@ruben-ayrapetyan Would you please review this PR?

**Comment by ruben-ayrapetyan** [comment]
@lemmaa, yes, sure.

**Comment by ruben-ayrapetyan** [comment]
Looks good to me

**Pull request merged**
