### PR TITLE
ECMAScript Parameters cannot be passed in collections anymore

### PR DESCRIPTION
**Pull request by zherczeg**
Lots of code removal.

### CODE REVIEW

**Comment by LaszloLango** [comment]
Please measure this patch on RPi2. The change looks good.

**Comment by bzsolt** [comment]
The RPi2 results with run-perf-test.sh
master: [91a0514](https://github.com/Samsung/jerryscript/commit/91a0514fab38ed7c82e1791d5ff9813a889ddaea)

Benchmark | RSS<br>(+ is better) | Perf<br>(+ is better)
---------: | --------- | ---------
3d-cube.js | `  96k ->   84k      `<br>`            +12.500%` | `  2.700s ->   2.707s                      `<br>`                 -0.247%  (+-0.919%) : [≈]`
access-binary-trees.js | `  84k ->   80k      `<br>`             +4.762%` | `  1.482s ->   1.443s                      `<br>`                 +2.588%  (+-0.724%) : [+]`
access-fannkuch.js | `  40k ->   36k      `<br>`            +10.000%` | `  8.052s ->   8.273s                      `<br>`                 -2.753%  (+-1.174%) : [-]`
access-nbody.js | `  48k ->   40k      `<br>`            +16.667%` | `  3.232s ->   3.205s                      `<br>`                 +0.825%  (+-0.973%) : [≈]`
bitops-3bit-bits-in-byte.js | `  32k ->   32k      `<br>`             +0.000%` | `  1.755s ->   1.780s                      `<br>`                 -1.425%  (+-1.300%) : [-]`
bitops-bits-in-byte.js | `  32k ->   32k      `<br>`             +0.000%` | `  2.690s ->   2.730s                      `<br>`                 -1.487%  (+-0.955%) : [-]`
bitops-bitwise-and.js | `  32k ->   32k      `<br>`             +0.000%` | `  3.722s ->   3.798s                      `<br>`                 -2.060%  (+-0.737%) : [-]`
controlflow-recursive.js | ` 152k ->  176k      `<br>`            -15.789%` | `  0.900s ->   0.920s                      `<br>`                 -2.222%  (+-0.000%) : [-]`
crypto-aes.js | ` 124k ->  120k      `<br>`             +3.226%` | `  4.747s ->   4.742s                      `<br>`                 +0.105%  (+-0.823%) : [≈]`
crypto-md5.js | ` 184k ->  180k      `<br>`             +2.174%` | ` 21.162s ->  21.098s                      `<br>`                 +0.300%  (+-0.791%) : [≈]`
crypto-sha1.js | ` 132k ->  124k      `<br>`             +6.061%` | `  9.600s ->   9.615s                      `<br>`                 -0.156%  (+-0.999%) : [≈]`
date-format-tofte.js | `  64k ->   60k      `<br>`             +6.250%` | `  2.230s ->   2.238s                      `<br>`                 -0.374%  (+-0.983%) : [≈]`
date-format-xparb.js | `  64k ->   60k      `<br>`             +6.250%` | `  1.145s ->   1.110s                      `<br>`                 +3.057%  (+-0.763%) : [+]`
math-cordic.js | `  32k ->   32k      `<br>`             +0.000%` | `  3.042s ->   3.060s                      `<br>`                 -0.603%  (+-0.799%) : [≈]`
math-partial-sums.js | `  36k ->   32k      `<br>`            +11.111%` | `  1.855s ->   1.713s                      `<br>`                 +7.637%  (+-0.852%) : [+]`
math-spectral-norm.js | `  44k ->   36k      `<br>`            +18.182%` | `  1.538s ->   1.535s                      `<br>`                 +0.216%  (+-0.730%) : [≈]`
string-fasta.js | `  48k ->   44k      `<br>`             +8.333%` | ^[OF`  4.610s ->   4.543s                      `<br>`                 +1.446%  (+-0.533%) : [+]`
Geometric mean: | RSS reduction: `5.575%` | Speed up: `0.315% (+-0.211%) : [+]`

**Comment by LaszloLango** [comment]
LGTM

**Comment by LaszloLango** [comment]
Precommit failed
```./jerry-core/ecma/operations/ecma-objects-arguments.cpp:270: error: comment missmatch. (Current: ecma_op_create_arguments_object_array_args, Expected: ecma_op_create_arguments_object)
./jerry-core/vm/vm.cpp:2463: error: comment missmatch. (Current: vm_run_array_args, Expected: vm_run)
 vera++ static checks failed. See output above for details.```

**Comment by zherczeg** [comment]
Fixed

**Pull request merged**
