### PR TITLE
API documentation update under docs.

### PR DESCRIPTION
**Pull request by ktorpi**
Links to JerryScript API reference page (https://samsung.github.io/jerryscript/API/) are inserted.

JerryScript-DCO-1.0-Signed-off-by: István Kádár ikadar@inf.u-szeged.hu

### CODE REVIEW

**Comment by zherczeg** [comment]
I see it is just delete. The reference points to the removed text?

**Comment by LaszloLango** [comment]
@zherczeg, yes. The markdown file of the API reference was duplicated. This PR makes the further maintenance easier. My only note is that #1099 should be merged at first. LGTM, after that.

**Comment by zherczeg** [comment]
Ok. LGTM then.

**Comment by lemmaa** [comment]
@LaszloLango , in my personal opinion, keeping API documents with source code is better then this. Historically, we moved documents from web site to source code repository. How about find the way to sync documents from source repository to web pages? Composing the web site in `*.md` file is one of reason for it. :)

**Comment by LaszloLango** [comment]
@lemmaa, It is still in the source code repository. It's only moved to the `gh-pages` branch. We already had two md files for the same information (one in the master branch and one in gh-pages branch). The API reference is still in a markdown file and you can make pull requests to change it, so we can do better reviews before land. This is what @ktorpi does in nowadays. See: #1038, #1053, #1069, 1099, #1106 and #1117

I think this was your goal too, if you are referring to this issue: https://github.com/Samsung/iotjs/issues/315.  But please fix me if I misunderstood something. :)

**Comment by lemmaa** [comment]
@LaszloLango, In my comment, `document with source code repository` means in same branch. I think documents must be distributed with source code in single tar ball, when it releases. Is it suitable to make a single tar ball from source code and document in separate branch? 

Form another point of view, version syncs between source code and document also looks complicate on separate branch.

**Pull request merged**
