### PR TITLE
Implement String.prototype.substring()

### PR DESCRIPTION
**Pull request by lvidacs**
JerryScript-DCO-1.0-Signed-off-by: Laszlo Vidacs lvidacs.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by lvidacs** [comment]
See history in PR #244

**Comment by galpeter** [comment]
lgtm

**Comment by egavrin** [comment]
Good to me

**Comment by galpeter** [comment]
Rebased & merged: https://github.com/Samsung/jerryscript/commit/6d86c4b2e1448d8dea8314a8ba5a57bf1167a679

**Pull request closed without merging**
