### PR TITLE
Refactoring the build system

### PR DESCRIPTION
**Pull request by akiss77**
* Removed unused or unnecessary parts from various make files
* Eliminated lots of duplications from Makefile with the help of
  macros.
* Split tools/precommit.sh to its independent components:
  * the part that checks the existence of the "signed off" text in
    commit messages
    (this on got factored out to tools/check-signed-off.sh),
  * the part that uses vera++ for style checking (this one got
    factored out to tools/check-vera.sh),
  * the part that invokes targets in the cmake-generated build
    directory, and
  * the part that performs various tests (these latter two got
    moved into the Makefile).
* Added ninja build system support (e.g., `make NINJA=1`).
* Updated leading documentation comments (they were somewhat
  stale).
* Tried to keep the target names exactly the same as they were --
  almost succeeded... (some changes are intentional, and are
  subject to personal preferences).

JerryScript-DCO-1.0-Signed-off-by: Akos Kiss akiss@inf.u-szeged.hu

### CODE REVIEW

**Comment by akiss77** [comment]
WIP patch, still conflicts with some recently landed patches. All thoughts and feedbacks are most welcome.

**Comment by akiss77** [comment]
Side note: with ninja, a full precommit run became somewhat faster (3m53s -> 3m22s).

**Comment by LaszloLango** [comment]
#868 is merged into master.

**Comment by akiss77** [comment]
Rebased to master, but still WIP.

**Comment by LaszloLango** [comment]
This may be related: #664

**Comment by akiss77** [comment]
Improved & rebased & pushed. It starts looking OK to me so reviews/feedbacks can start rolling.

**Comment by LaszloLango** [comment]
Please rename `tests/jerry-test-suite/compact_profile_list` to `tests/jerry-test-suite/compact-profile-list` and `tests/jerry-test-suite/precommit_test_list` to `tests/jerry-test-suite/precommit-test-list`

**Comment by akiss77** [comment]
Renamed.

**Comment by LaszloLango** [comment]
@akiss77, thanks. LGTM

**Comment by akiss77** [comment]
Merged f959ba9

**Pull request merged**
