### PR TITLE
Fix broken links on project website

### PR DESCRIPTION
**Pull request by yoseo**
Fix broken links on github page website using **site.github.url** ( ref : https://jekyllrb.com/docs/github-pages/ )

> JerryScript-DCO-1.0-Signed-off-by: Ryan Youngtae Seo ryan@cworkers.kr

### CODE REVIEW

**Comment by tilmannOSG** [comment]
@yoseo Thank your very much for fixing the web site!  
The changes look good to me, can you please either squash both commits into one or start one pull request per commit? (we prefer to only merge one commit per pull request).  
Please add a DCO Signed-off-by line to the commit message as well :) You can find out more about the DCO at https://github.com/Samsung/jerryscript/wiki/JerryScript-Developer's-Certificate-of-Origin  
Essentially what you need to do to sign the DCO is to add a line like this at the end of the commit message (with your real name and email address):

> JerryScript-DCO-1.0-Signed-off-by: Random J Developer random@developer.example.org

BTW looks like you have a small typo in one of the commit messages: bronken -> broken

**Comment by akosthekiss** [comment]
A question, perhaps to ourselves: I see .md files being changed by this PR. Are these copies of the files under the docs directory of the master branch, kept in sync manually? Does anyone know of a more maintainable way?

**Comment by LaszloLango** [comment]
@akosthekiss, yes. IMHO, this should be fixed in `tools/update-webpage.sh`

**Comment by tilmannOSG** [comment]
@akosthekiss Right, that's a good point. To my knowledge the current process is to run update-webpage.sh and manually commit the files to the gh-pages branch. Moving to this process was a first step to store all the documentation in one place (the master branch). The script adds some additional information to the MD files to create a proper web site.  
I guess in terms of maintainability it would be nice if we could just reference the MD files from the master branch directly? (though I'm not sure how easy it is to embed them).

**Comment by tilmannOSG** [comment]
@LaszloLango I agree that this needs to be fixed in the script but I think we can just go ahead in merging @yoseo commits to get the out web site out of the broken state. Once his commits are merged we can tweak the script to produce identical output.

**Comment by tilmannOSG** [comment]
@yoseo Thank you for the updates! LGTM from my side.

**Comment by LaszloLango** [comment]
LGTM

**Pull request merged**
