### PR TITLE
remove 15.07.04.02-002.js from jerry-test-suites

### PR DESCRIPTION
**Pull request by chunseoklee**
Number.prototype.toString([radix]) is implementation-dependant.

IoT.js-DCO-1.0-Signed-off-by: Chunseok Lee chunseok.lee@samsung.com

### CODE REVIEW

**Comment by egavrin** [comment]
Fix precommit please.

**Comment by chunseoklee** [comment]
precommit error fixed.

**Comment by egavrin** [comment]
Good to me.

**Comment by egavrin** [comment]
PS. I think we need to revise our test suite, since it may have other issues.

**Comment by zherczeg** [comment]
LGTM

**Comment by egavrin** [comment]
Merged cb0087b5170493f358c8f9b84d8049d6bc47bf55

**Pull request closed without merging**
