### PR TITLE
Fix RIOT port after API update

### PR DESCRIPTION
**Pull request by LaszloLango**
JerryScript-DCO-1.0-Signed-off-by: László Langó llango.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by robertsipka** [comment]
LGTM (informally)

**Comment by zherczeg** [comment]
LGTM

**Comment by tilmannOSG** [comment]
The name of the OS is just RIOT :)

**Comment by LaszloLango** [comment]
@tilmannOSG, I see. I've updated the commit message and rebased to the current master.

**Comment by akosthekiss** [comment]
LGTM

**Pull request merged**
