### PR TITLE
Fix preparsing of variable declaration lists, which are not divided by a semicolon

### PR DESCRIPTION
**Pull request by sand1k**
This patch fixes the following tests from test262:
- ch13/13.2/13.2-1-s.js
- ch13/13.2/13.2-3-s.js

### CODE REVIEW

**Comment by egavrin** [comment]
Good to me

**Comment by ruben-ayrapetyan** [comment]
Looks good to me

**Comment by zherczeg** [comment]
The patch looks good to me.

However, I don't see any test case in the patch and the comment only mention two test262 files. Please at least add an example here as a comment, so I can see what is fixed.

**Comment by ruben-ayrapetyan** [comment]
@zherczeg, the changes fix handling of two consecutive VariableDeclarationList statements, that are not divided by a semicolon.

**Comment by egavrin** [comment]
@zherczeg example:
```cpp
var foo = function () {
      this.caller = 12;
}
var obj = new foo();
```

**Comment by zherczeg** [comment]
Ok, land it.

**Pull request merged**
