### PR TITLE
Makefile refactor

### PR DESCRIPTION
**Pull request by akiss77**
A loosely coupled, intentionally non-squashed set of patches improving the Makefile. Key property of the patches is that they don't change any current default behaviour (but extend possibilities, improve readability of recipes, or fix latent bugs).

### CODE REVIEW

**Comment by egavrin** [comment]
Related issue: #108

**Comment by egavrin** [comment]
Good to me

**Comment by akiss77** [comment]
Ah, but I got it wrong. `tee` is a tricky beast and swallows the exit code of the command earlier in the pipe. (Which would cause always-successful builds from make's perspective.) Will update the PR with fix ASAP.

**Comment by akiss77** [comment]
FYI: updated and rebased

**Comment by egavrin** [comment]
@akiss77 is possible to split logs into two streams `stdout` and `stderr` and put them into separate logs? The idea is to print all errors on screen after in case of build failure - not to analyze logs by eye.

**Comment by akiss77** [comment]
@egavrin can/will experiment. Could we have that as a follow-up, however? This patch set keeps everything working as was before by default. The log splitting approach would cause a change in the default behaviour.

**Comment by egavrin** [comment]
@akiss77 of course :)

Good to me.

**Comment by ruben-ayrapetyan** [comment]
Looks good to me

**Comment by akiss77** [comment]
Seen two LGTMs, thanks, I'll push.

**Comment by akiss77** [comment]
Merged at 6038173e76265ab30ae7b5b70a4d20633e1de9b7

**Pull request closed without merging**
