### PR TITLE
targets: add nuttx interpreter build

### PR DESCRIPTION
**Pull request by seanshpark**
JerryScript-DCO-1.0-Signed-off-by: SaeHie Park saehie.park@samsung.com

### CODE REVIEW

**Comment by seanshpark** [comment]
any one interested to review? :)

**Comment by zherczeg** [comment]
In general argument, function comments are missing from main-nuttx.cpp. I think there was a discussion to reduce the number of main-**.cpp files. Do we really need a separated file this platform?

**Comment by tinysense** [comment]
@zherczeg , well, this PR was before merging main-*.cpp and I wasn't thinking of  adding snapshot for arm/nuttx.

**Comment by seanshpark** [comment]
@zherczeg , well,I wasn't thinking of adding snapshot to arm/nuttx and when I made this code, linux and darwin was in separate files. And I think for embed target ports, I prefer more simple codes as an example and entry.

**Comment by zherczeg** [comment]
Is it still a valid PR or you plan some changes?

**Comment by seanshpark** [comment]
Hope to merge as is but if you think better to use main-unix.cpp, I need to check how it works.

**Comment by LaszloLango** [comment]
The main reason of merging `main-linux.cpp` and `main-darwin.cpp` was that they were almost identical. I think it is OK to place in a separate file, because `main-nuttx.cpp` is different.

**Comment by zherczeg** [comment]
Ok I was just asking.

**Comment by zherczeg** [comment]
LGTM, though it would be good to reduce code duplications on these main-*.cpp files in a followup patches.

**Comment by LaszloLango** [comment]
Landed (ef1252e29e5777ed8010e7a02a0c4c1c62530201)

**Pull request closed without merging**
