### PR TITLE
Add syntax check for return from global scope/eval.

### PR DESCRIPTION
**Pull request by egavrin**
Related issue: #129

JerryScript-DCO-1.0-Signed-off-by: Evgeny Gavrin e.gavrin@samsung.com

### CODE REVIEW

**Comment by ruben-ayrapetyan** [comment]
Looks good to me.

**Comment by ruben-ayrapetyan** [comment]
Could you, please, add "Related issue:" to commit message?

**Comment by egavrin** [comment]
@ruben-ayrapetyan done

**Comment by ruben-ayrapetyan** [comment]
@egavrin, thank you!

**Comment by galpeter** [comment]
looks good to me

**Comment by zherczeg** [comment]
lgtm

**Pull request merged**
