### PR TITLE
Add locale part of the toString in the Date object

### PR DESCRIPTION
**Pull request by szledan**
JerryScript-DCO-1.0-Signed-off-by: Szilard Ledan szledan.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by galpeter** [comment]
by `local` don't you mean `locale`?

**Comment by szledan** [comment]
Yes, it's true.. (Typo)

**Comment by egavrin** [comment]
Ok for mew

**Comment by galpeter** [comment]
yep, lgtm also

**Comment by egavrin** [comment]
I'll push

**Comment by egavrin** [comment]
Merged at 351df6184c62b74f1246e9400fb5180d94882baf

**Pull request merged**
