### PR TITLE
Add merge commit support to tools/check-signed-off.sh and…

### PR DESCRIPTION
**Pull request by akiss77**
…re-introduce signed-off check to Travis CI

JerryScript-DCO-1.0-Signed-off-by: Akos Kiss akiss@inf.u-szeged.hu

### CODE REVIEW

**Comment by akiss77** [comment]
If this PR gets Travis green now, then we can reintroduce signed-off checks. (If not, then it needs some more fiddling.)

**Comment by akiss77** [comment]
related to #895

**Comment by LaszloLango** [comment]
LGTM

**Comment by zherczeg** [comment]
LGTM

**Pull request merged**
