### PR TITLE
Optimize lit_find_literal_by_utf8_string.

### PR DESCRIPTION
**Pull request by sand1k**
Calculate and compare hash of the searched string.

### CODE REVIEW

**Comment by ruben-ayrapetyan** [comment]
Looks good to me

**Comment by zherczeg** [comment]
Looks good to me. Did you do any measurements? I am just curious about the gain of this change.

**Comment by sand1k** [comment]
@zherczeg, the test generated with a command
`for i in `seq 1 1 10000`; do echo "a$i = b$i;" >> temp.js; done`
executes 3 times faster with this patch.

**Comment by egavrin** [comment]
I'll land

**Pull request merged**
