### PR TITLE
Fix generation of empty completion value in ecma_reject_put.

### PR DESCRIPTION
**Pull request by egavrin**
Related issue: #114

JerryScript-DCO-1.0-Signed-off-by: Evgeny Gavrin e.gavrin@samsung.com

### CODE REVIEW

**Comment by ruben-ayrapetyan** [comment]
Looks good to me

**Comment by galpeter** [comment]
What was the problem with the first solution (https://github.com/Samsung/jerryscript/commit/ae321fc3ad901736775688041ec3e7b2c873ccec)? Where you changed the `ecma_make_simple_completion_value` assert?

For me it seems natural that if there is a call to the `ecma_make_simple_completion_value` then I would be able to create an empty value as the name `ECMA_SIMPLE_VALUE_EMPTY` clearly states that it is a simple value.

**Comment by egavrin** [comment]
@galpeter technically it's assumed that we can only create `ECMA_SIMPLE_VALUE_EMPTY` from constant value, not from `ecma_simple_value_t`. So, it's the way to check that this assumption is respected.

**Comment by galpeter** [comment]
Looks good to me.

**Pull request merged**
