### PR TITLE
SplitMatch operation should not set its return array element with [[Put]]

### PR DESCRIPTION
**Pull request by yichoi**
Related issue: #1076 

I used `ecma_builtin_helper_def_prop` instead of `ecma_create_named_data_property` and `ecma_set_named_data_property_value` because the length of the result array should be set correctly.

### CODE REVIEW

**Comment by zherczeg** [comment]
The ecma_builtin_helper_def_prop is a heavyweight (costly) function, so we should only call it if we feel that the code is not a hot path. On the longer run perhaps we should create another (internal) put which ignores the prototype.

**Comment by LaszloLango** [comment]
IMHO, this is not a hot path. I'm OK with this fix. LGTM

Here are the RPi2 results:

Benchmark | Perf (sec) |
----: | ----: | 
3d-cube.js | 0.937 -> 0.942 : -0.451% | 
3d-raytrace.js | 1.111 -> 1.119 : -0.748% | 
access-binary-trees.js | 0.591 -> 0.588 : +0.539% | 
access-fannkuch.js | 2.376 -> 2.383 : -0.284% | 
access-nbody.js | 1.077 -> 1.073 : +0.371% | 
bitops-3bit-bits-in-byte.js | 0.572 -> 0.575 : -0.414% | 
bitops-bits-in-byte.js | 0.853 -> 0.853 : +0.009% | 
bitops-bitwise-and.js | 1.010 -> 0.965 : +4.432% | 
bitops-nsieve-bits.js | 1.795 -> 1.797 : -0.136% | 
controlflow-recursive.js | 0.378 -> 0.383 : -1.075% | 
crypto-aes.js | 1.110 -> 1.117 : -0.628% | 
crypto-md5.js | 0.731 -> 0.735 : -0.581% | 
crypto-sha1.js | 0.695 -> 0.699 : -0.571% | 
date-format-tofte.js | 0.866 -> 0.861 : +0.620% | 
date-format-xparb.js | 0.473 -> 0.461 : +2.406% | 
math-cordic.js | 1.327 -> 1.329 : -0.203% | 
math-partial-sums.js | 0.726 -> 0.711 : +1.989% | 
math-spectral-norm.js | 0.580 -> 0.585 : -0.783% | 
string-base64.js | 2.062 -> 2.035 : +1.316% | 
string-fasta.js | 1.386 -> 1.387 : -0.058% | 
Geometric mean: | +0.296% | 

Binary sizes (bytes)
17d1d37cca:157304
1ed036f914:157864

**Comment by zherczeg** [comment]
Ok, lets do it this way.
LGTM

**Comment by akosthekiss** [comment]
please, rebase to latest master

**Comment by yichoi** [comment]
Rebased the code.

**Pull request merged**
