### PR TITLE
Refactor fromCharCode including support for surrogate pairs.

### PR DESCRIPTION
**Pull request by zherczeg**
JerryScript-DCO-1.0-Signed-off-by: Zoltan Herczeg zherczeg@inf.u-szeged.hu

### CODE REVIEW

**Comment by zherczeg** [comment]
Fixes 4 test262 tests.

**Comment by sand1k** [comment]
LGTM.

**Comment by kkristof** [comment]
Looks good to me.

**Comment by zherczeg** [comment]
Thank you, I will land the patch

**Comment by zherczeg** [comment]
Landed in 8df6cdd1e9b63aa2c15ea6f7d7f2bf00adef642b

**Pull request closed without merging**
