### PR TITLE
Initialize the timeval struct fields, because the gettimeofday() may …

### PR DESCRIPTION
**Pull request by robertsipka**
…not fill these.

JerryScript-DCO-1.0-Signed-off-by: Robert Sipka rsipka.uszeged@partner.samsung.com

### CODE REVIEW

**Comment by zherczeg** [comment]
LGTM

**Comment by robertsipka** [comment]
I've updated the patch.

**Comment by LaszloLango** [comment]
LGTM

**Comment by akiss77** [comment]
LGTM

**Pull request merged**
