### PR TITLE
Fix processing of elision in array literal

### PR DESCRIPTION
**Pull request by sand1k**
Fixes the following tests from test262:
 - ch15/15.2/15.2.3/15.2.3.6/15.2.3.6-4-159.js
 - ch15/15.2/15.2.3/15.2.3.6/15.2.3.6-4-160.js
 - ch15/15.2/15.2.3/15.2.3.7/15.2.3.7-6-a-155.js
 - ch15/15.2/15.2.3/15.2.3.7/15.2.3.7-6-a-156.js
 - ch15/15.4/15.4.4/15.4.4.14/15.4.4.14-9-a-10.js
 - ch15/15.4/15.4.4/15.4.4.14/15.4.4.14-9-b-1.js
 - ch15/15.4/15.4.4/15.4.4.14/15.4.4.14-9-b-i-15.js
 - ch15/15.4/15.4.4/15.4.4.14/15.4.4.14-9-b-i-7.js
 - ch15/15.4/15.4.4/15.4.4.15/15.4.4.15-8-a-10.js
 - ch15/15.4/15.4.4/15.4.4.15/15.4.4.15-8-b-1.js
 - ch15/15.4/15.4.4/15.4.4.15/15.4.4.15-8-b-i-15.js
 - ch15/15.4/15.4.4/15.4.4.15/15.4.4.15-8-b-i-7.js
 - ch15/15.4/15.4.4/15.4.4.16/15.4.4.16-7-b-11.js
 - ch15/15.4/15.4.4/15.4.4.16/15.4.4.16-7-b-7.js
 - ch15/15.4/15.4.4/15.4.4.16/15.4.4.16-7-c-i-16.js
 - ch15/15.4/15.4.4/15.4.4.16/15.4.4.16-7-c-i-8.js
 - ch15/15.4/15.4.4/15.4.4.17/15.4.4.17-7-b-11.js
 - ch15/15.4/15.4.4/15.4.4.17/15.4.4.17-7-b-7.js
 - ch15/15.4/15.4.4/15.4.4.17/15.4.4.17-7-c-i-16.js
 - ch15/15.4/15.4.4/15.4.4.17/15.4.4.17-7-c-i-8.js
 - ch15/15.4/15.4.4/15.4.4.18/15.4.4.18-7-b-11.js
 - ch15/15.4/15.4.4/15.4.4.18/15.4.4.18-7-b-7.js
 - ch15/15.4/15.4.4/15.4.4.18/15.4.4.18-7-c-i-16.js
 - ch15/15.4/15.4.4/15.4.4.18/15.4.4.18-7-c-i-8.js
 - ch15/15.4/15.4.4/15.4.4.19/15.4.4.19-8-b-11.js
 - ch15/15.4/15.4.4/15.4.4.19/15.4.4.19-8-b-7.js
 - ch15/15.4/15.4.4/15.4.4.19/15.4.4.19-8-c-i-16.js
 - ch15/15.4/15.4.4/15.4.4.19/15.4.4.19-8-c-i-8.js
 - ch15/15.4/15.4.4/15.4.4.20/15.4.4.20-9-b-11.js
 - ch15/15.4/15.4.4/15.4.4.20/15.4.4.20-9-b-7.js
 - ch15/15.4/15.4.4/15.4.4.20/15.4.4.20-9-c-i-16.js
 - ch15/15.4/15.4.4/15.4.4.20/15.4.4.20-9-c-i-8.js
 - ch15/15.4/15.4.4/15.4.4.21/15.4.4.21-8-b-iii-1-16.js
 - ch15/15.4/15.4.4/15.4.4.21/15.4.4.21-8-b-iii-1-8.js
 - ch15/15.4/15.4.4/15.4.4.21/15.4.4.21-9-b-11.js
 - ch15/15.4/15.4.4/15.4.4.21/15.4.4.21-9-b-20.js
 - ch15/15.4/15.4.4/15.4.4.21/15.4.4.21-9-b-24.js
 - ch15/15.4/15.4.4/15.4.4.21/15.4.4.21-9-b-7.js
 - ch15/15.4/15.4.4/15.4.4.21/15.4.4.21-9-c-i-16.js
 - ch15/15.4/15.4.4/15.4.4.21/15.4.4.21-9-c-i-8.js
 - ch15/15.4/15.4.4/15.4.4.22/15.4.4.22-8-b-iii-1-16.js
 - ch15/15.4/15.4.4/15.4.4.22/15.4.4.22-8-b-iii-1-8.js
 - ch15/15.4/15.4.4/15.4.4.22/15.4.4.22-9-b-11.js
 - ch15/15.4/15.4.4/15.4.4.22/15.4.4.22-9-b-20.js
 - ch15/15.4/15.4.4/15.4.4.22/15.4.4.22-9-b-24.js
 - ch15/15.4/15.4.4/15.4.4.22/15.4.4.22-9-b-7.js
 - ch15/15.4/15.4.4/15.4.4.22/15.4.4.22-9-c-i-16.js
 - ch15/15.4/15.4.4/15.4.4.22/15.4.4.22-9-c-i-8.js

### CODE REVIEW

**Comment by egavrin** [comment]
Good to me

**Comment by zherczeg** [comment]
LGTM

**Comment by galpeter** [comment]
FYI: last time I did this fix (https://github.com/Samsung/jerryscript/pull/319) I was told that adding a new simple value is not a good way to resolve the issue. Issue report: #356

**Comment by sand1k** [comment]
@galpeter, thank you for pointing this. We'll discuss it and, probably, make an update then.

**Comment by ruben-ayrapetyan** [comment]
I think new simple value is not necessary in the case.

**Comment by ruben-ayrapetyan** [comment]
The only thing that seems to be necessary is support of empty `varg`, and update of `array_decl` opcode handler.

**Pull request merged**
