### PR TITLE
Enable build on Mac OS X with clang

### PR DESCRIPTION
**Pull request by lemmaa**
* Add build target 'darwin'
* Modify compiler options to work with clang
* Support 'jerry-libc' on Mac OS X

For MPU target build, install `gcc-arm-none-eabi` tool chain using `Homebrew` as following.
````
brew tap PX4/homebrew-px4
brew update
brew install gcc-arm-none-eabi
````
https://pixhawk.org/dev/toolchain_installation_mac

JerryScript-DCO-1.0-Signed-off-by: Sung-Jae Lee sjlee@mail.com

### CODE REVIEW

**Comment by lemmaa** [comment]
@egavrin, @zherczeg please, review.

**Comment by egavrin** [comment]
LGTM

**Comment by lemmaa** [comment]
@zherczeg @galpeter This PR is becoming outdated. Do you have a chance to review this? or is it OK just merge with only review of @egavrin ?

**Comment by galpeter** [comment]
@lemmaa, ah.. sorry for the big delay. I can't test this (would love to:)) as I don't have access to a Mac, but the patch looks good to me.

**Comment by lemmaa** [comment]
Create new PR https://github.com/Samsung/jerryscript/pull/628 to resolve merge conflict to https://github.com/Samsung/jerryscript/commit/b318de46a632b5b96822f7827f89d3829869adf3 and https://github.com/Samsung/jerryscript/commit/fdf38ab2eb918cc4a7f263ef66174d358bf46fa2 .

**Pull request closed without merging**
