### PR TITLE
Assertion fix for missing class names.

### PR DESCRIPTION
**Pull request by LaszloLango**
Assertion 'builtin_id == ECMA_BUILTIN_ID_TYPE_ERROR_THROWER' failed in ecma_object_get_class_name.

JerryScript-DCO-1.0-Signed-off-by: László Langó llango.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by LaszloLango** [comment]
related issue: #285

**Comment by galpeter** [comment]
Please add test cases also :)

**Comment by LaszloLango** [comment]
@galpeter, sorry, I forgot to add it. I've updated the PR, please check.

**Comment by ruben-ayrapetyan** [comment]
Looks good to me.

**Comment by egavrin** [comment]
`make push`

**Comment by galpeter** [comment]
lgtm

**Comment by kkristof** [comment]
Rebased and merged in e9a5b34d1d21f2d3543ce656bdb20ef5095eaec7

**Pull request closed without merging**
