### PR TITLE
Support REPL for Linux

### PR DESCRIPTION
**Pull request by wateret**
REPL for LInux. It runs REPL when no JS files given from command line.
For #704.

### CODE REVIEW

**Comment by seanshpark** [comment]
+1
How about printing name and version when executed?
```
JerryScript version x.y.z
jerry>
```
BTW, do we have version string?

**Comment by egavrin** [comment]
@seanshpark we have commit hash and branch, no versio yet.

```cpp
/**
 * Jerry engine build date
 */
const char *jerry_build_date = JERRY_BUILD_DATE;

/**
 * Jerry engine build commit hash
 */
const char *jerry_commit_hash = JERRY_COMMIT_HASH;

/**
 * Jerry engine build branch name
 */
const char *jerry_branch_name = JERRY_BRANCH_NAME;

```

**Comment by galpeter** [comment]
Do I see correctly that we can specify the `is_dump_snapshot_mode` and repl mode at the same time? Is that what we want?

**Comment by wateret** [comment]
@galpeter `is_repl_mode` is set to true when `files_counter == 0 && exec_snapshots_count == 0`. So basically Jerry turns to REPL mode when no files given. Plus, when options like `--exec-snapshot` or `--dump-snapshot` are given, we'll see an error just like current master.
```
$ ./jerry --exec-snapshot
Error: wrong format of the arguments
```

**Comment by galpeter** [comment]
the PR seems ok to me, but we'll need to adapt this for the darwin main file also. IMHO: we'll need to come up a way to minimize differences (btw: do we need the darwin main at all?)

**Comment by egavrin** [comment]
> btw: do we need the darwin main at all?
We don't.

**Comment by wateret** [comment]
@egavrin, @galpeter Rebased to current master. Now that #819 is merged, can I push this PR?

**Comment by galpeter** [comment]
@wateret yeah, its good to push.

**Comment by LaszloLango** [comment]
Landed (0e88e819eb0f2c6e3c63e9b73246133b21a84059)

**Pull request closed without merging**
