### PR TITLE
Make the string trim method unicode tolerant.

### PR DESCRIPTION
**Pull request by galpeter**
Fixes issue #426

JerryScript-DCO-1.0-Signed-off-by: Peter Gal pgal.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by egavrin** [comment]
Good to me

**Comment by kkristof** [comment]
Looks good to me.

**Comment by egavrin** [comment]
`make push`

**Comment by dbatyai** [comment]
Landed: af56cd8465e530428e5be6ac9074201a21e36da3

**Pull request closed without merging**
