### PR TITLE
Remove exec mode from non-executable files

### PR DESCRIPTION
**Pull request by akiss77**
JerryScript-DCO-1.0-Signed-off-by: Akos Kiss akiss@inf.u-szeged.hu

### CODE REVIEW

**Comment by akiss77** [comment]
I know that this is a truly minor thing but they have been irritating me for a while. I don't know why these files were executable in the first place.

**Comment by LaszloLango** [comment]
This annoys me too. :) Thanks for fixing this. LGTM

**Comment by franc0is** [comment]
LGTM

**Comment by zherczeg** [comment]
LGTM

**Pull request merged**
